### ISSUE TITLE
[Errno 10061]

### ISSUE THREAD

**Issue by ReddPool** [XaF/TraktForVLC#18]
Hey,

So it's me again ...
I'm still having errors in my debug log and it's still not scrobbling on the website ...
``` batch
2015-05-30 13:07:58,311::VLCRemote::DEBUG::-> Sending: is_playing
2015-05-30 13:08:00,125::TraktForVLC::ERROR::An unknown error occurred
Traceback (most recent call last):
  File "C:\TraktForVLC-master\TraktForVLC.py", line 397, in run
    self.main()
  File "C:\TraktForVLC-master\TraktForVLC.py", line 434, in main
    vlcStatus = vlc.is_playing()
  File "C:\TraktForVLC-master\vlcrc\__init__.py", line 152, in is_playing
    playing = self._command('is_playing', fn_re, raw=True)
  File "C:\TraktForVLC-master\vlcrc\__init__.py", line 106, in _command
    index, match, cmd_ret = self.cnx.expect([return_re], self.timeout)
  File "C:\Python27\lib\telnetlib.py", line 655, in expect
    return self._expect_with_select(list, timeout)
  File "C:\Python27\lib\telnetlib.py", line 755, in _expect_with_select
    self.fill_rawq()
  File "C:\Python27\lib\telnetlib.py", line 576, in fill_rawq
    buf = self.sock.recv(50)
error: [Errno 10054] Une connexion existante a dû être fermée par l’hôte distant
2015-05-30 13:08:07,128::TraktForVLC::INFO::Could not find VLC running at localhost:4222
2015-05-30 13:08:07,128::TraktForVLC::DEBUG::Make sure your VLC player is running with --extraintf=rc --rc-host=localhost:4222 --rc-quiet
Traceback (most recent call last):
  File "C:\TraktForVLC-master\TraktForVLC.py", line 407, in main
    vlc = VLCRemote(self.vlc_ip, self.vlc_port)
  File "C:\TraktForVLC-master\vlcrc\__init__.py", line 38, in __init__
    self.cnx = telnetlib.Telnet(hostname, port)
  File "C:\Python27\lib\telnetlib.py", line 211, in __init__
    self.open(host, port, timeout)
  File "C:\Python27\lib\telnetlib.py", line 227, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "C:\Python27\lib\socket.py", line 575, in create_connection
    raise err
error: [Errno 10061] Aucune connexion n’a pu être établie car l’ordinateur cible l’a expressément refusée
2015-05-30 13:08:07,130::TraktForVLC::DEBUG::reset cache view status (None)
```

Any ideas ?

**Comment by XaF** [comment]
These messages just means the connexion was lost between `TraktForVLC` and VLC. Probably if you closed VLC at that moment for the 10054, and the 10061 is just that VLC was already closed.
