### ISSUE TITLE
Episode is being marked as watched multiple times.

### ISSUE THREAD

**Issue by Phmager** [XaF/TraktForVLC#20]
This is the log:
Windows 8.1 and Python 2.7

2015-06-25 22:11:37,334::TraktForVLC::INFO::Sense8 - 1x08 state : 83%
2015-06-25 22:11:37,334::TraktForVLC::DEBUG::main::Video: {'duration': 2977, 'show_imdbid': u'tt2431438', 'episode': u'8', 'title': u'Sense8', 'tv': True, 'imdbid': u'tt3963678', 'percentage': 83, 'year': u'2015-06-05', 'season': u'1'}
2015-06-25 22:11:37,334::TraktForVLC::DEBUG::main::This video is scrobbled : False
2015-06-25 22:11:37,334::TraktForVLC::DEBUG::main::Trying to mark Sense8 - 1x08 watching on Trakt...
2015-06-25 22:11:37,334::TraktClient::DEBUG::Sending POST to https://api-v2launch.trakt.tv/scrobble/start data {"app_date": "2015-04-14", "progress": 83, "app_version": "1.3.0-rc1", "episode": {"season": "1", "number": "8"}, "show": {"ids": {"imdb": "tt2431438"}}}
2015-06-25 22:11:37,334::TraktClient::DEBUG::{"app_date": "2015-04-14", "progress": 83, "app_version": "1.3.0-rc1", "episode": {"season": "1", "number": "8"}, "show": {"ids": {"imdb": "tt2431438"}}}
2015-06-25 22:11:37,334::requests.packages.urllib3.connectionpool::INFO::Starting new HTTPS connection (1): api-v2launch.trakt.tv
2015-06-25 22:11:56,302::requests.packages.urllib3.connectionpool::DEBUG::"POST /scrobble/start HTTP/1.1" 201 290
2015-06-25 22:11:56,302::TraktForVLC::INFO::Sense8 - 1x08 is currently watching on Trakt...
2015-06-25 22:12:01,303::VLCRemote::DEBUG::-> Sending: is_playing
2015-06-25 22:12:01,303::VLCRemote::DEBUG::<- Received: 1
2015-06-25 22:12:01,303::VLCRemote::DEBUG::-> Sending: get_length
2015-06-25 22:12:01,303::VLCRemote::DEBUG::<- Received: 2977
2015-06-25 22:12:01,303::VLCRemote::DEBUG::-> Sending: get_title
2015-06-25 22:12:01,303::VLCRemote::DEBUG::<- Received: Sense8 S01E08.mp4
2015-06-25 22:12:01,303::VLCRemote::DEBUG::-> Sending: get_time
2015-06-25 22:12:01,309::VLCRemote::DEBUG::<- Received: 2511
2015-06-25 22:12:01,309::TraktForVLC::INFO::Sense8 - 1x08 state : 84%
2015-06-25 22:12:01,309::TraktForVLC::DEBUG::main::Video: {'duration': 2977, 'show_imdbid': u'tt2431438', 'episode': u'8', 'title': u'Sense8', 'tv': True, 'imdbid': u'tt3963678', 'percentage': 84, 'year': u'2015-06-05', 'season': u'1'}
2015-06-25 22:12:01,309::TraktForVLC::DEBUG::main::This video is scrobbled : False
2015-06-25 22:12:01,309::TraktForVLC::DEBUG::main::Trying to mark Sense8 - 1x08 watching on Trakt...
2015-06-25 22:12:01,309::TraktClient::DEBUG::Sending POST to https://api-v2launch.trakt.tv/scrobble/start data {"app_date": "2015-04-14", "progress": 84, "app_version": "1.3.0-rc1", "episode": {"season": "1", "number": "8"}, "show": {"ids": {"imdb": "tt2431438"}}}
2015-06-25 22:12:01,309::TraktClient::DEBUG::{"app_date": "2015-04-14", "progress": 84, "app_version": "1.3.0-rc1", "episode": {"season": "1", "number": "8"}, "show": {"ids": {"imdb": "tt2431438"}}}
2015-06-25 22:12:01,309::requests.packages.urllib3.connectionpool::INFO::Starting new HTTPS connection (1): api-v2launch.trakt.tv
2015-06-25 22:13:01,946::requests.packages.urllib3.connectionpool::DEBUG::"POST /scrobble/start HTTP/1.1" 504 None
2015-06-25 22:13:01,950::TraktForVLC::ERROR::An error occurred while trying to mark as watching Sense8 - 1x08
Traceback (most recent call last):
  File "../TraktForVLC.py", line 554, in main
    self.get_episode(video))
  File "C:\TraktForVLC\TraktClient.py", line 420, in startWatching
    return self.__watching('start', imdb_id, progress, episode)
  File "C:\TraktForVLC\TraktClient.py", line 377, in __watching
    progress=progress)
  File "C:\TraktForVLC\TraktClient.py", line 416, in __watchingEpisode
    return self.__scrobble(action, data)
  File "C:\TraktForVLC\TraktClient.py", line 358, in __scrobble
    stream.reason))
TraktError: Unable to start episode: 504 Gateway Time-out
2015-06-25 22:13:06,951::VLCRemote::DEBUG::-> Sending: is_playing
2015-06-25 22:13:06,951::VLCRemote::DEBUG::<- Received: 1
2015-06-25 22:13:06,951::VLCRemote::DEBUG::-> Sending: get_length
2015-06-25 22:13:06,951::VLCRemote::DEBUG::<- Received: 2977
2015-06-25 22:13:06,951::VLCRemote::DEBUG::-> Sending: get_title
2015-06-25 22:13:06,951::VLCRemote::DEBUG::<- Received: Sense8 S01E08.mp4
2015-06-25 22:13:06,951::VLCRemote::DEBUG::-> Sending: get_time
2015-06-25 22:13:06,957::VLCRemote::DEBUG::<- Received: 2577
2015-06-25 22:13:06,957::TraktForVLC::INFO::Sense8 - 1x08 state : 86%
2015-06-25 22:13:06,957::TraktForVLC::DEBUG::main::Video: {'duration': 2977, 'show_imdbid': u'tt2431438', 'episode': u'8', 'title': u'Sense8', 'tv': True, 'imdbid': u'tt3963678', 'percentage': 86, 'year': u'2015-06-05', 'season': u'1'}
2015-06-25 22:13:06,957::TraktForVLC::DEBUG::main::This video is scrobbled : False
2015-06-25 22:13:06,957::TraktForVLC::DEBUG::main::Trying to mark Sense8 - 1x08 watching on Trakt...
2015-06-25 22:13:06,957::TraktClient::DEBUG::Sending POST to https://api-v2launch.trakt.tv/scrobble/start data {"app_date": "2015-04-14", "progress": 86, "app_version": "1.3.0-rc1", "episode": {"season": "1", "number": "8"}, "show": {"ids": {"imdb": "tt2431438"}}}
2015-06-25 22:13:06,957::TraktClient::DEBUG::{"app_date": "2015-04-14", "progress": 86, "app_version": "1.3.0-rc1", "episode": {"season": "1", "number": "8"}, "show": {"ids": {"imdb": "tt2431438"}}}
2015-06-25 22:13:06,957::requests.packages.urllib3.connectionpool::INFO::Starting new HTTPS connection (1): api-v2launch.trakt.tv
2015-06-25 22:13:44,042::requests.packages.urllib3.connectionpool::DEBUG::"POST /scrobble/start HTTP/1.1" 201 290
2015-06-25 22:13:44,046::TraktForVLC::INFO::Sense8 - 1x08 is currently watching on Trakt...
2015-06-25 22:13:49,049::VLCRemote::DEBUG::-> Sending: is_playing
2015-06-25 22:13:49,049::VLCRemote::DEBUG::<- Received: 1
2015-06-25 22:13:49,049::VLCRemote::DEBUG::-> Sending: get_length
2015-06-25 22:13:49,049::VLCRemote::DEBUG::<- Received: 2977
2015-06-25 22:13:49,049::VLCRemote::DEBUG::-> Sending: get_title
2015-06-25 22:13:49,053::VLCRemote::DEBUG::<- Received: Sense8 S01E08.mp4
2015-06-25 22:13:49,053::VLCRemote::DEBUG::-> Sending: get_time
2015-06-25 22:13:49,053::VLCRemote::DEBUG::<- Received: 2619
2015-06-25 22:13:49,053::TraktForVLC::INFO::Sense8 - 1x08 state : 87%
2015-06-25 22:13:49,053::TraktForVLC::DEBUG::main::Video: {'duration': 2977, 'show_imdbid': u'tt2431438', 'episode': u'8', 'title': u'Sense8', 'tv': True, 'imdbid': u'tt3963678', 'percentage': 87, 'year': u'2015-06-05', 'season': u'1'}
2015-06-25 22:13:49,053::TraktForVLC::DEBUG::main::This video is scrobbled : False
2015-06-25 22:13:49,053::TraktForVLC::DEBUG::main::Trying to mark Sense8 - 1x08 watching on Trakt...
2015-06-25 22:13:49,053::TraktClient::DEBUG::Sending POST to https://api-v2launch.trakt.tv/scrobble/start data {"app_date": "2015-04-14", "progress": 87, "app_version": "1.3.0-rc1", "episode": {"season": "1", "number": "8"}, "show": {"ids": {"imdb": "tt2431438"}}}
2015-06-25 22:13:49,053::TraktClient::DEBUG::{"app_date": "2015-04-14", "progress": 87, "app_version": "1.3.0-rc1", "episode": {"season": "1", "number": "8"}, "show": {"ids": {"imdb": "tt2431438"}}}
2015-06-25 22:13:49,053::requests.packages.urllib3.connectionpool::INFO::Starting new HTTPS connection (1): api-v2launch.trakt.tv
2015-06-25 22:14:13,588::requests.packages.urllib3.connectionpool::DEBUG::"POST /scrobble/start HTTP/1.1" 504 None
2015-06-25 22:14:13,592::TraktForVLC::ERROR::An error occurred while trying to mark as watching Sense8 - 1x08
Traceback (most recent call last):
  File "../TraktForVLC.py", line 554, in main
    self.get_episode(video))
  File "C:\TraktForVLC\TraktClient.py", line 420, in startWatching
    return self.__watching('start', imdb_id, progress, episode)
  File "C:\TraktForVLC\TraktClient.py", line 377, in __watching
    progress=progress)
  File "C:\TraktForVLC\TraktClient.py", line 416, in __watchingEpisode
    return self.__scrobble(action, data)
  File "C:\TraktForVLC\TraktClient.py", line 358, in __scrobble
    stream.reason))
TraktError: Unable to start episode: 504 Gateway Time-out
2015-06-25 22:14:18,592::VLCRemote::DEBUG::-> Sending: is_playing
2015-06-25 22:14:18,592::VLCRemote::DEBUG::<- Received: 1
2015-06-25 22:14:18,592::VLCRemote::DEBUG::-> Sending: get_length
2015-06-25 22:14:18,592::VLCRemote::DEBUG::<- Received: 2977
2015-06-25 22:14:18,592::VLCRemote::DEBUG::-> Sending: get_title
2015-06-25 22:14:18,592::VLCRemote::DEBUG::<- Received: Sense8 S01E08.mp4
2015-06-25 22:14:18,592::VLCRemote::DEBUG::-> Sending: get_time
2015-06-25 22:14:18,598::VLCRemote::DEBUG::<- Received: 2648
2015-06-25 22:14:18,598::TraktForVLC::INFO::Sense8 - 1x08 state : 88%
2015-06-25 22:14:18,598::TraktForVLC::DEBUG::main::Video: {'duration': 2977, 'show_imdbid': u'tt2431438', 'episode': u'8', 'title': u'Sense8', 'tv': True, 'imdbid': u'tt3963678', 'percentage': 88, 'year': u'2015-06-05', 'season': u'1'}
2015-06-25 22:14:18,598::TraktForVLC::DEBUG::main::This video is scrobbled : False
2015-06-25 22:14:18,598::TraktForVLC::DEBUG::main::Trying to mark Sense8 - 1x08 watching on Trakt...
2015-06-25 22:14:18,598::TraktClient::DEBUG::Sending POST to https://api-v2launch.trakt.tv/scrobble/start data {"app_date": "2015-04-14", "progress": 88, "app_version": "1.3.0-rc1", "episode": {"season": "1", "number": "8"}, "show": {"ids": {"imdb": "tt2431438"}}}
2015-06-25 22:14:18,598::TraktClient::DEBUG::{"app_date": "2015-04-14", "progress": 88, "app_version": "1.3.0-rc1", "episode": {"season": "1", "number": "8"}, "show": {"ids": {"imdb": "tt2431438"}}}
2015-06-25 22:14:18,598::requests.packages.urllib3.connectionpool::INFO::Starting new HTTPS connection (1): api-v2launch.trakt.tv
2015-06-25 22:14:44,088::requests.packages.urllib3.connectionpool::DEBUG::"POST /scrobble/start HTTP/1.1" 504 None
2015-06-25 22:14:44,092::TraktForVLC::ERROR::An error occurred while trying to mark as watching Sense8 - 1x08
Traceback (most recent call last):
  File "../TraktForVLC.py", line 554, in main
    self.get_episode(video))
  File "C:\TraktForVLC\TraktClient.py", line 420, in startWatching
    return self.__watching('start', imdb_id, progress, episode)
  File "C:\TraktForVLC\TraktClient.py", line 377, in __watching
    progress=progress)
  File "C:\TraktForVLC\TraktClient.py", line 416, in __watchingEpisode
    return self.__scrobble(action, data)
  File "C:\TraktForVLC\TraktClient.py", line 358, in __scrobble
    stream.reason))
TraktError: Unable to start episode: 504 Gateway Time-out
2015-06-25 22:14:49,092::VLCRemote::DEBUG::-> Sending: is_playing
2015-06-25 22:14:49,092::VLCRemote::DEBUG::<- Received: 1
2015-06-25 22:14:49,092::VLCRemote::DEBUG::-> Sending: get_length
2015-06-25 22:14:49,092::VLCRemote::DEBUG::<- Received: 2977
2015-06-25 22:14:49,092::VLCRemote::DEBUG::-> Sending: get_title
2015-06-25 22:14:49,098::VLCRemote::DEBUG::<- Received: Sense8 S01E08.mp4
2015-06-25 22:14:49,098::VLCRemote::DEBUG::-> Sending: get_time
2015-06-25 22:14:49,098::VLCRemote::DEBUG::<- Received: 2679
2015-06-25 22:14:49,098::TraktForVLC::INFO::Sense8 - 1x08 state : 89%
2015-06-25 22:14:49,098::TraktForVLC::DEBUG::main::Video: {'duration': 2977, 'show_imdbid': u'tt2431438', 'episode': u'8', 'title': u'Sense8', 'tv': True, 'imdbid': u'tt3963678', 'percentage': 89, 'year': u'2015-06-05', 'season': u'1'}
2015-06-25 22:14:49,098::TraktForVLC::DEBUG::main::This video is scrobbled : False
2015-06-25 22:14:49,098::TraktForVLC::DEBUG::main::Trying to mark Sense8 - 1x08 watching on Trakt...
2015-06-25 22:14:49,098::TraktClient::DEBUG::Sending POST to https://api-v2launch.trakt.tv/scrobble/start data {"app_date": "2015-04-14", "progress": 89, "app_version": "1.3.0-rc1", "episode": {"season": "1", "number": "8"}, "show": {"ids": {"imdb": "tt2431438"}}}
2015-06-25 22:14:49,098::TraktClient::DEBUG::{"app_date": "2015-04-14", "progress": 89, "app_version": "1.3.0-rc1", "episode": {"season": "1", "number": "8"}, "show": {"ids": {"imdb": "tt2431438"}}}
2015-06-25 22:14:49,098::requests.packages.urllib3.connectionpool::INFO::Starting new HTTPS connection (1): api-v2launch.trakt.tv
2015-06-25 22:15:04,641::requests.packages.urllib3.connectionpool::DEBUG::"POST /scrobble/start HTTP/1.1" 504 None
2015-06-25 22:15:04,644::TraktForVLC::ERROR::An error occurred while trying to mark as watching Sense8 - 1x08
Traceback (most recent call last):
  File "../TraktForVLC.py", line 554, in main
    self.get_episode(video))
  File "C:\TraktForVLC\TraktClient.py", line 420, in startWatching
    return self.__watching('start', imdb_id, progress, episode)
  File "C:\TraktForVLC\TraktClient.py", line 377, in __watching
    progress=progress)
  File "C:\TraktForVLC\TraktClient.py", line 416, in __watchingEpisode
    return self.__scrobble(action, data)
  File "C:\TraktForVLC\TraktClient.py", line 358, in __scrobble
    stream.reason))
TraktError: Unable to start episode: 504 Gateway Time-out
2015-06-25 22:15:09,645::VLCRemote::DEBUG::-> Sending: is_playing
2015-06-25 22:15:09,647::VLCRemote::DEBUG::<- Received: 1
2015-06-25 22:15:09,647::VLCRemote::DEBUG::-> Sending: get_length
2015-06-25 22:15:09,647::VLCRemote::DEBUG::<- Received: 2977
2015-06-25 22:15:09,647::VLCRemote::DEBUG::-> Sending: get_title
2015-06-25 22:15:09,647::VLCRemote::DEBUG::<- Received: Sense8 S01E08.mp4
2015-06-25 22:15:09,647::VLCRemote::DEBUG::-> Sending: get_time
2015-06-25 22:15:09,648::VLCRemote::DEBUG::<- Received: 2699
2015-06-25 22:15:09,648::TraktForVLC::INFO::Sense8 - 1x08 state : 90%
2015-06-25 22:15:09,648::TraktForVLC::DEBUG::main::Video: {'duration': 2977, 'show_imdbid': u'tt2431438', 'episode': u'8', 'title': u'Sense8', 'tv': True, 'imdbid': u'tt3963678', 'percentage': 90, 'year': u'2015-06-05', 'season': u'1'}
2015-06-25 22:15:09,648::TraktForVLC::DEBUG::main::This video is scrobbled : False
2015-06-25 22:15:09,648::TraktForVLC::INFO::Scrobbling Sense8 - 1x08 to Trakt...
2015-06-25 22:15:09,648::TraktClient::DEBUG::Sending POST to https://api-v2launch.trakt.tv/scrobble/stop data {"app_date": "2015-04-14", "progress": 90, "app_version": "1.3.0-rc1", "episode": {"season": "1", "number": "8"}, "show": {"ids": {"imdb": "tt2431438"}}}
2015-06-25 22:15:09,648::TraktClient::DEBUG::{"app_date": "2015-04-14", "progress": 90, "app_version": "1.3.0-rc1", "episode": {"season": "1", "number": "8"}, "show": {"ids": {"imdb": "tt2431438"}}}
2015-06-25 22:15:09,648::requests.packages.urllib3.connectionpool::INFO::Starting new HTTPS connection (1): api-v2launch.trakt.tv
2015-06-25 22:15:26,325::requests.packages.urllib3.connectionpool::DEBUG::"POST /scrobble/stop HTTP/1.1" 504 None
2015-06-25 22:15:26,329::TraktForVLC::ERROR::An error occurred while trying to scrobble
Traceback (most recent call last):
  File "../TraktForVLC.py", line 532, in main
    self.get_episode(video))
  File "C:\TraktForVLC\TraktClient.py", line 424, in stopWatching
    return self.__watching('stop', imdb_id, progress, episode)
  File "C:\TraktForVLC\TraktClient.py", line 377, in __watching
    progress=progress)
  File "C:\TraktForVLC\TraktClient.py", line 416, in __watchingEpisode
    return self.__scrobble(action, data)
  File "C:\TraktForVLC\TraktClient.py", line 358, in __scrobble
    stream.reason))
TraktError: Unable to stop episode: 504 Gateway Time-out
2015-06-25 22:15:31,334::VLCRemote::DEBUG::-> Sending: is_playing
2015-06-25 22:15:31,334::VLCRemote::DEBUG::<- Received: 1
2015-06-25 22:15:31,334::VLCRemote::DEBUG::-> Sending: get_length
2015-06-25 22:15:31,334::VLCRemote::DEBUG::<- Received: 2977
2015-06-25 22:15:31,334::VLCRemote::DEBUG::-> Sending: get_title
2015-06-25 22:15:31,334::VLCRemote::DEBUG::<- Received: Sense8 S01E08.mp4
2015-06-25 22:15:31,334::VLCRemote::DEBUG::-> Sending: get_time
2015-06-25 22:15:31,338::VLCRemote::DEBUG::<- Received: 2721
2015-06-25 22:15:31,338::TraktForVLC::INFO::Sense8 - 1x08 state : 91%
2015-06-25 22:15:31,338::TraktForVLC::DEBUG::main::Video: {'duration': 2977, 'show_imdbid': u'tt2431438', 'episode': u'8', 'title': u'Sense8', 'tv': True, 'imdbid': u'tt3963678', 'percentage': 91, 'year': u'2015-06-05', 'season': u'1'}
2015-06-25 22:15:31,338::TraktForVLC::DEBUG::main::This video is scrobbled : False
2015-06-25 22:15:31,338::TraktForVLC::INFO::Scrobbling Sense8 - 1x08 to Trakt...
2015-06-25 22:15:31,338::TraktClient::DEBUG::Sending POST to https://api-v2launch.trakt.tv/scrobble/stop data {"app_date": "2015-04-14", "progress": 91, "app_version": "1.3.0-rc1", "episode": {"season": "1", "number": "8"}, "show": {"ids": {"imdb": "tt2431438"}}}
2015-06-25 22:15:31,338::TraktClient::DEBUG::{"app_date": "2015-04-14", "progress": 91, "app_version": "1.3.0-rc1", "episode": {"season": "1", "number": "8"}, "show": {"ids": {"imdb": "tt2431438"}}}
2015-06-25 22:15:31,338::requests.packages.urllib3.connectionpool::INFO::Starting new HTTPS connection (1): api-v2launch.trakt.tv
2015-06-25 22:16:28,239::requests.packages.urllib3.connectionpool::DEBUG::"POST /scrobble/stop HTTP/1.1" 504 None
2015-06-25 22:16:28,243::TraktForVLC::ERROR::An error occurred while trying to scrobble
Traceback (most recent call last):
  File "../TraktForVLC.py", line 532, in main
    self.get_episode(video))
  File "C:\TraktForVLC\TraktClient.py", line 424, in stopWatching
    return self.__watching('stop', imdb_id, progress, episode)
  File "C:\TraktForVLC\TraktClient.py", line 377, in __watching
    progress=progress)
  File "C:\TraktForVLC\TraktClient.py", line 416, in __watchingEpisode
    return self.__scrobble(action, data)
  File "C:\TraktForVLC\TraktClient.py", line 358, in __scrobble
    stream.reason))
TraktError: Unable to stop episode: 504 Gateway Time-out
2015-06-25 22:16:33,246::VLCRemote::DEBUG::-> Sending: is_playing
2015-06-25 22:16:33,247::VLCRemote::DEBUG::<- Received: 1
2015-06-25 22:16:33,247::VLCRemote::DEBUG::-> Sending: get_length
2015-06-25 22:16:33,247::VLCRemote::DEBUG::<- Received: 2977
2015-06-25 22:16:33,249::VLCRemote::DEBUG::-> Sending: get_title
2015-06-25 22:16:33,249::VLCRemote::DEBUG::<- Received: Sense8 S01E08.mp4
2015-06-25 22:16:33,249::VLCRemote::DEBUG::-> Sending: get_time
2015-06-25 22:16:33,250::VLCRemote::DEBUG::<- Received: 2783
2015-06-25 22:16:33,250::TraktForVLC::INFO::Sense8 - 1x08 state : 93%
2015-06-25 22:16:33,250::TraktForVLC::DEBUG::main::Video: {'duration': 2977, 'show_imdbid': u'tt2431438', 'episode': u'8', 'title': u'Sense8', 'tv': True, 'imdbid': u'tt3963678', 'percentage': 93, 'year': u'2015-06-05', 'season': u'1'}
2015-06-25 22:16:33,250::TraktForVLC::DEBUG::main::This video is scrobbled : False
2015-06-25 22:16:33,250::TraktForVLC::INFO::Scrobbling Sense8 - 1x08 to Trakt...
2015-06-25 22:16:33,250::TraktClient::DEBUG::Sending POST to https://api-v2launch.trakt.tv/scrobble/stop data {"app_date": "2015-04-14", "progress": 93, "app_version": "1.3.0-rc1", "episode": {"season": "1", "number": "8"}, "show": {"ids": {"imdb": "tt2431438"}}}
2015-06-25 22:16:33,250::TraktClient::DEBUG::{"app_date": "2015-04-14", "progress": 93, "app_version": "1.3.0-rc1", "episode": {"season": "1", "number": "8"}, "show": {"ids": {"imdb": "tt2431438"}}}
2015-06-25 22:16:33,252::requests.packages.urllib3.connectionpool::INFO::Starting new HTTPS connection (1): api-v2launch.trakt.tv
2015-06-25 22:16:34,582::requests.packages.urllib3.connectionpool::DEBUG::"POST /scrobble/stop HTTP/1.1" 201 292
2015-06-25 22:16:34,585::TraktForVLC::INFO::Sense8 - 1x08 scrobbled to Trakt !
2015-06-25 22:16:39,586::VLCRemote::DEBUG::-> Sending: is_playing
2015-06-25 22:16:39,586::VLCRemote::DEBUG::<- Received: 1
2015-06-25 22:16:39,586::VLCRemote::DEBUG::-> Sending: get_length
2015-06-25 22:16:39,586::VLCRemote::DEBUG::<- Received: 2977
2015-06-25 22:16:39,586::VLCRemote::DEBUG::-> Sending: get_title
2015-06-25 22:16:39,586::VLCRemote::DEBUG::<- Received: Sense8 S01E08.mp4
2015-06-25 22:16:39,586::VLCRemote::DEBUG::-> Sending: get_time
2015-06-25 22:16:39,586::VLCRemote::DEBUG::<- Received: 2789
2015-06-25 22:16:39,586::TraktForVLC::INFO::Sense8 - 1x08 state : 93%
2015-06-25 22:16:39,586::TraktForVLC::DEBUG::main::Video: {'duration': 2977, 'show_imdbid': u'tt2431438', 'episode': u'8', 'title': u'Sense8', 'tv': True, 'imdbid': u'tt3963678', 'percentage': 93, 'year': u'2015-06-05', 'season': u'1'}
2015-06-25 22:16:39,586::TraktForVLC::DEBUG::main::This video is scrobbled : True
2015-06-25 22:16:44,589::VLCRemote::DEBUG::-> Sending: is_playing
2015-06-25 22:16:44,589::VLCRemote::DEBUG::<- Received: 1
2015-06-25 22:16:44,591::VLCRemote::DEBUG::-> Sending: get_length
2015-06-25 22:16:44,591::VLCRemote::DEBUG::<- Received: 2977
2015-06-25 22:16:44,591::VLCRemote::DEBUG::-> Sending: get_title
2015-06-25 22:16:44,592::VLCRemote::DEBUG::<- Received: Sense8 S01E08.mp4
2015-06-25 22:16:44,592::VLCRemote::DEBUG::-> Sending: get_time
2015-06-25 22:16:44,592::VLCRemote::DEBUG::<- Received: 2794
2015-06-25 22:16:44,592::TraktForVLC::INFO::Sense8 - 1x08 state : 93%
2015-06-25 22:16:44,592::TraktForVLC::DEBUG::main::Video: {'duration': 2977, 'show_imdbid': u'tt2431438', 'episode': u'8', 'title': u'Sense8', 'tv': True, 'imdbid': u'tt3963678', 'percentage': 93, 'year': u'2015-06-05', 'season': u'1'}
2015-06-25 22:16:44,592::TraktForVLC::DEBUG::main::This video is scrobbled : True
2015-06-25 22:16:49,595::VLCRemote::DEBUG::-> Sending: is_playing
2015-06-25 22:16:49,595::VLCRemote::DEBUG::<- Received: 1
2015-06-25 22:16:49,595::VLCRemote::DEBUG::-> Sending: get_length
2015-06-25 22:16:49,595::VLCRemote::DEBUG::<- Received: 2977
2015-06-25 22:16:49,595::VLCRemote::DEBUG::-> Sending: get_title
2015-06-25 22:16:49,595::VLCRemote::DEBUG::<- Received: Sense8 S01E08.mp4
2015-06-25 22:16:49,595::VLCRemote::DEBUG::-> Sending: get_time
2015-06-25 22:16:49,596::VLCRemote::DEBUG::<- Received: 2799
2015-06-25 22:16:49,596::TraktForVLC::INFO::Sense8 - 1x08 state : 94%
2015-06-25 22:16:49,596::TraktForVLC::DEBUG::main::Video: {'duration': 2977, 'show_imdbid': u'tt2431438', 'episode': u'8', 'title': u'Sense8', 'tv': True, 'imdbid': u'tt3963678', 'percentage': 94, 'year': u'2015-06-05', 'season': u'1'}
2015-06-25 22:16:49,596::TraktForVLC::DEBUG::main::This video is scrobbled : True
2015-06-25 22:16:54,596::VLCRemote::DEBUG::-> Sending: is_playing
2015-06-25 22:16:54,596::VLCRemote::DEBUG::<- Received: 1
2015-06-25 22:16:54,596::VLCRemote::DEBUG::-> Sending: get_length
2015-06-25 22:16:54,596::VLCRemote::DEBUG::<- Received: 2977
2015-06-25 22:16:54,596::VLCRemote::DEBUG::-> Sending: get_title
2015-06-25 22:16:54,596::VLCRemote::DEBUG::<- Received: Sense8 S01E08.mp4
2015-06-25 22:16:54,596::VLCRemote::DEBUG::-> Sending: get_time
2015-06-25 22:16:54,596::VLCRemote::DEBUG::<- Received: 2804
2015-06-25 22:16:54,596::TraktForVLC::INFO::Sense8 - 1x08 state : 94%
2015-06-25 22:16:54,596::TraktForVLC::DEBUG::main::Video: {'duration': 2977, 'show_imdbid': u'tt2431438', 'episode': u'8', 'title': u'Sense8', 'tv': True, 'imdbid': u'tt3963678', 'percentage': 94, 'year': u'2015-06-05', 'season': u'1'}
2015-06-25 22:16:54,596::TraktForVLC::DEBUG::main::This video is scrobbled : True
2015-06-25 22:16:59,602::VLCRemote::DEBUG::-> Sending: is_playing
2015-06-25 22:16:59,602::VLCRemote::DEBUG::<- Received: 1
2015-06-25 22:16:59,602::VLCRemote::DEBUG::-> Sending: get_length
2015-06-25 22:16:59,602::VLCRemote::DEBUG::<- Received: 2977
2015-06-25 22:16:59,602::VLCRemote::DEBUG::-> Sending: get_title
2015-06-25 22:16:59,602::VLCRemote::DEBUG::<- Received: Sense8 S01E08.mp4
2015-06-25 22:16:59,602::VLCRemote::DEBUG::-> Sending: get_time
2015-06-25 22:16:59,602::VLCRemote::DEBUG::<- Received: 2809
2015-06-25 22:16:59,602::TraktForVLC::INFO::Sense8 - 1x08 state : 94%
2015-06-25 22:16:59,608::TraktForVLC::DEBUG::main::Video: {'duration': 2977, 'show_imdbid': u'tt2431438', 'episode': u'8', 'title': u'Sense8', 'tv': True, 'imdbid': u'tt3963678', 'percentage': 94, 'year': u'2015-06-05', 'season': u'1'}
2015-06-25 22:16:59,608::TraktForVLC::DEBUG::main::This video is scrobbled : True
2015-06-25 22:17:04,608::VLCRemote::DEBUG::-> Sending: is_playing

**Comment by XaF** [comment]
It mostly seems like it's Trakt that was answering to `TraktForVLC` that the request was not accepted, when it really was. So I can't consider this a bug of `TraktForVLC`, and there's nothing I can really do for that at this point!
