### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by edmgt** [XaF/TraktForVLC#28]
For the last week or so this tool doesn't seem to work anymore. Does this only happen to me or is it a known issue? My log output:
```
2015-11-20 12:56:05,346::TraktForVLC::INFO::## TraktForVLC v1.3.0-rc1 Breaking Bad
2015-11-20 12:56:05,346::TraktForVLC::INFO::## Copyright (C) 2014-2015  RaphaÃ«l Beamonte <raphael.beamonte@gmail.com>
2015-11-20 12:56:05,346::TraktForVLC::INFO::##
2015-11-20 12:56:05,346::TraktForVLC::INFO::## TraktForVLC is distributed in the hope that it will be useful, but
2015-11-20 12:56:05,346::TraktForVLC::INFO::## with ABSOLUTELY NO WARRANTY. This is free software; you are welcome
2015-11-20 12:56:05,348::TraktForVLC::INFO::## to redistribute and/or modify it under the terms of the GPL2.
2015-11-20 12:56:05,348::TraktForVLC::INFO::
2015-11-20 12:56:05,368::TraktForVLC::DEBUG::Running on Windows-8-6.2.9200, with Python 2.7.10
2015-11-20 12:56:05,380::requests.packages.urllib3.connectionpool::INFO::Starting new HTTPS connection (1): api.github.com
2015-11-20 12:56:06,500::requests.packages.urllib3.connectionpool::DEBUG::"GET /repos/XaF/TraktForVLC/releases HTTP/1.1" 200 None
2015-11-20 12:56:06,503::TraktForVLC::INFO::VERSION:TraktForVLC is up to date
2015-11-20 12:56:06,505::TraktForVLC::INFO::Logger level is set to DEBUG
2015-11-20 12:56:06,505::TraktForVLC::INFO::-- Will scrobble movies ? Yes
2015-11-20 12:56:06,505::TraktForVLC::INFO::-- Will scrobble tv shows ? Yes
2015-11-20 12:56:06,505::TraktForVLC::INFO::-- Will we mark movies as being watched ? Yes
2015-11-20 12:56:06,505::TraktForVLC::INFO::-- Will we mark tv shows as being watched ? Yes
2015-11-20 12:56:06,505::TraktForVLC::INFO::-- Videos will be scrobbled after 90% of their duration has been exceeded
2015-11-20 12:56:06,506::TraktForVLC::INFO::-- Timer set to 5 secs
2015-11-20 12:56:06,506::TraktForVLC::INFO::-- Video will be marked as "is watching" from 5 secs
2015-11-20 12:56:06,506::TraktForVLC::INFO::Listening VLC to localhost:4222
2015-11-20 12:56:06,506::TraktClient::DEBUG::TraktClient logger initialized
2015-11-20 12:56:06,506::TraktClient::DEBUG::TraktClient will use PIN Auth
2015-11-20 12:56:06,506::TraktForVLC::DEBUG::reset cache (None, None)
2015-11-20 12:56:06,509::VLCRemote::DEBUG::-> Sending: is_playing
2015-11-20 12:56:09,510::TraktForVLC::ERROR::An unknown error occurred
Traceback (most recent call last):
  File "D:\Dropbox\Failai\TraktForVLC\TraktForVLC.py", line 397, in run
    self.main()
  File "D:\Dropbox\Failai\TraktForVLC\TraktForVLC.py", line 434, in main
    vlcStatus = vlc.is_playing()
  File "D:\Dropbox\Failai\TraktForVLC\vlcrc\__init__.py", line 152, in is_playing
    playing = self._command('is_playing', fn_re, raw=True)
  File "D:\Dropbox\Failai\TraktForVLC\vlcrc\__init__.py", line 109, in _command
    'Pattern: %s\nReceived: %s' % (return_re.pattern, cmd_ret))
VLCBadReturn: Pattern: ^(?!status change:)>?\s*(?P<playing>\d+)
?

Received: 
2015-11-20 12:56:14,513::VLCRemote::DEBUG::-> Sending: is_playing
2015-11-20 12:56:17,515::TraktForVLC::ERROR::An unknown error occurred
Traceback (most recent call last):
  File "D:\Dropbox\Failai\TraktForVLC\TraktForVLC.py", line 397, in run
    self.main()
  File "D:\Dropbox\Failai\TraktForVLC\TraktForVLC.py", line 434, in main
    vlcStatus = vlc.is_playing()
  File "D:\Dropbox\Failai\TraktForVLC\vlcrc\__init__.py", line 152, in is_playing
    playing = self._command('is_playing', fn_re, raw=True)
  File "D:\Dropbox\Failai\TraktForVLC\vlcrc\__init__.py", line 109, in _command
    'Pattern: %s\nReceived: %s' % (return_re.pattern, cmd_ret))
VLCBadReturn: Pattern: ^(?!status change:)>?\s*(?P<playing>\d+)
?
```

**Comment by XaF** [comment]
Hm, it seems VLC is the problem here. Have you set up VLC RC correctly? (using RC and not OLDRC)

**Comment by edmgt** [comment]
I actually cannot set rc. If I put rc instead of oldrc and exit vlc, field becomes blank. Is there a way to change it outside from vlc client?

**Comment by XaF** [comment]
Yeah, it is possible "rc" do not stays in the field, but as long as you don't rewrite over your config, rc should be activated.

**Comment by edmgt** [comment]
Interestingly enough putting rc and NOT checking "Remote control interface" checkbox seems to have done the trick! I did, however, need a new pin from trakt for some reason. Anyways, thanks for your help!
