### ISSUE TITLE
No tv show nor movie found for the current playing video when streaming to VLC on OS X

### ISSUE THREAD

**Issue by alessandrodallafina** [XaF/TraktForVLC#32]
Hi there, 

I'm having a strange issue where TraktForVLC doesn't recognize the movie I'm streaming to VLC. Not sure where the problem is. I'm using a MacBook Pro OS X El Capitan 10.11.1 with VLC 2.2.1. 

The settings seem fine to me but when debugging TraktForVLC I see no scrobbling even if I tweak the scrobble setting down to 1%. It always say:

`"No tv show nor movie found for the current playing video"`

Sometimes it doesn't get recognized, it appears to be my local URL and some other times even if the title is right I still see "No movie found [...]".

Do you know how I can fix it by any chance? Thanks :)

```
2015-12-28 08:49:46,808::TraktForVLC::INFO::## TraktForVLC v1.3.0-rc1 Breaking Bad
2015-12-28 08:49:46,808::TraktForVLC::INFO::## Copyright (C) 2014-2015  Raphaël Beamonte <raphael.beamonte@gmail.com>
2015-12-28 08:49:46,808::TraktForVLC::INFO::##
2015-12-28 08:49:46,808::TraktForVLC::INFO::## TraktForVLC is distributed in the hope that it will be useful, but
2015-12-28 08:49:46,808::TraktForVLC::INFO::## with ABSOLUTELY NO WARRANTY. This is free software; you are welcome
2015-12-28 08:49:46,808::TraktForVLC::INFO::## to redistribute and/or modify it under the terms of the GPL2.
2015-12-28 08:49:46,808::TraktForVLC::INFO::
2015-12-28 08:49:46,819::TraktForVLC::DEBUG::Running on Darwin-15.0.0-x86_64-i386-64bit, with Python 2.7.10
2015-12-28 08:49:47,267::requests.packages.urllib3.connectionpool::INFO::Starting new HTTPS connection (1): api.github.com
2015-12-28 08:49:47,479::requests.packages.urllib3.connectionpool::DEBUG::"GET /repos/XaF/TraktForVLC/releases HTTP/1.1" 200 None
2015-12-28 08:49:47,484::TraktForVLC::INFO::VERSION:TraktForVLC is up to date
2015-12-28 08:49:47,484::TraktForVLC::INFO::Logger level is set to DEBUG
2015-12-28 08:49:47,484::TraktForVLC::INFO::-- Will scrobble movies ? Yes
2015-12-28 08:49:47,484::TraktForVLC::INFO::-- Will scrobble tv shows ? Yes
2015-12-28 08:49:47,484::TraktForVLC::INFO::-- Will we mark movies as being watched ? Yes
2015-12-28 08:49:47,484::TraktForVLC::INFO::-- Will we mark tv shows as being watched ? Yes
2015-12-28 08:49:47,485::TraktForVLC::INFO::-- Videos will be scrobbled after 90% of their duration has been exceeded
2015-12-28 08:49:47,485::TraktForVLC::INFO::-- Timer set to 5 secs
2015-12-28 08:49:47,485::TraktForVLC::INFO::-- Video will be marked as "is watching" from 5 secs
2015-12-28 08:49:47,485::TraktForVLC::INFO::Listening VLC to localhost:4222
2015-12-28 08:49:47,485::TraktClient::DEBUG::TraktClient logger initialized
2015-12-28 08:49:47,485::TraktClient::DEBUG::TraktClient will use PIN Auth
2015-12-28 08:49:47,485::TraktForVLC::DEBUG::reset cache (None, None)
2015-12-28 08:49:47,489::VLCRemote::DEBUG::VLC version is 2.2.1
2015-12-28 08:49:47,489::VLCRemote::DEBUG::-> Sending: is_playing
2015-12-28 08:49:47,489::VLCRemote::DEBUG::<- Received: 1
2015-12-28 08:49:47,490::VLCRemote::DEBUG::cleaning cache
2015-12-28 08:49:47,490::VLCRemote::DEBUG::<- Received: >
2015-12-28 08:49:47,490::VLCRemote::DEBUG::-> Sending: get_length
2015-12-28 08:49:47,490::VLCRemote::DEBUG::<- Received: 2848
2015-12-28 08:49:47,491::VLCRemote::DEBUG::cleaning cache
2015-12-28 08:49:47,491::VLCRemote::DEBUG::<- Received: >
2015-12-28 08:49:47,491::VLCRemote::DEBUG::-> Sending: get_title
2015-12-28 08:49:47,492::VLCRemote::DEBUG::<- Received: http://127.0.0.1:52104/
2015-12-28 08:49:47,492::VLCRemote::DEBUG::cleaning cache
2015-12-28 08:49:47,492::VLCRemote::DEBUG::<- Received: >
2015-12-28 08:49:47,492::VLCRemote::DEBUG::-> Sending: get_time
2015-12-28 08:49:47,492::VLCRemote::DEBUG::<- Received: 6
2015-12-28 08:49:47,493::TraktForVLC::DEBUG::main::New file:  (2848)
2015-12-28 08:49:47,493::TraktForVLC::DEBUG::reset cache (, 2848)
2015-12-28 08:49:47,493::TraktForVLC::INFO::Not able to parse a tvshow from the file title
2015-12-28 08:49:47,493::TraktForVLC::INFO::No matching movie found for video playing
2015-12-28 08:49:47,493::TraktForVLC::DEBUG::get_Movie::Here's to help debug
Traceback (most recent call last):
  File "/Users/Alessandro/TraktForVLC/TraktForVLC.py", line 651, in get_Movie
    title = now_playing['title']
TypeError: 'bool' object has no attribute '__getitem__'
2015-12-28 08:49:47,493::TraktForVLC::INFO::No tv show nor movie found for the current playing video
2015-12-28 08:49:52,497::VLCRemote::DEBUG::cleaning cache
2015-12-28 08:49:52,497::VLCRemote::DEBUG::<- Received: VLC media player 2.2.1 Terry Pratchett (Weatherwax)
Command Line Interface initialized. Type `help' for help.
>
2015-12-28 08:49:52,497::VLCRemote::DEBUG::-> Sending: is_playing
2015-12-28 08:49:52,498::VLCRemote::DEBUG::<- Received: 1
2015-12-28 08:49:52,498::VLCRemote::DEBUG::cleaning cache
2015-12-28 08:49:52,498::VLCRemote::DEBUG::<- Received: >
2015-12-28 08:49:52,498::VLCRemote::DEBUG::-> Sending: get_length
2015-12-28 08:49:52,498::VLCRemote::DEBUG::<- Received: 2848
2015-12-28 08:49:52,498::VLCRemote::DEBUG::cleaning cache
2015-12-28 08:49:52,498::VLCRemote::DEBUG::<- Received: >
2015-12-28 08:49:52,498::VLCRemote::DEBUG::-> Sending: get_title
2015-12-28 08:49:52,498::VLCRemote::DEBUG::<- Received: http://127.0.0.1:52104/
2015-12-28 08:49:52,499::VLCRemote::DEBUG::cleaning cache
2015-12-28 08:49:52,499::VLCRemote::DEBUG::<- Received: >
2015-12-28 08:49:52,499::VLCRemote::DEBUG::-> Sending: get_time
2015-12-28 08:49:52,499::VLCRemote::DEBUG::<- Received: 11
2015-12-28 08:49:52,499::TraktForVLC::INFO::No tv show nor movie found for the current playing video
2015-12-28 08:49:57,504::VLCRemote::DEBUG::VLC version is 2.2.1
2015-12-28 08:49:57,504::VLCRemote::DEBUG::-> Sending: is_playing
2015-12-28 08:49:57,504::VLCRemote::DEBUG::<- Received: 1
2015-12-28 08:49:57,504::VLCRemote::DEBUG::cleaning cache
2015-12-28 08:49:57,504::VLCRemote::DEBUG::<- Received: >
2015-12-28 08:49:57,504::VLCRemote::DEBUG::-> Sending: get_length
2015-12-28 08:49:57,505::VLCRemote::DEBUG::<- Received: 2848
2015-12-28 08:49:57,505::VLCRemote::DEBUG::cleaning cache
2015-12-28 08:49:57,505::VLCRemote::DEBUG::<- Received: >
2015-12-28 08:49:57,505::VLCRemote::DEBUG::-> Sending: get_title
2015-12-28 08:49:57,505::VLCRemote::DEBUG::<- Received: http://127.0.0.1:52104/
2015-12-28 08:49:57,505::VLCRemote::DEBUG::cleaning cache
2015-12-28 08:49:57,505::VLCRemote::DEBUG::<- Received: >
2015-12-28 08:49:57,505::VLCRemote::DEBUG::-> Sending: get_time
2015-12-28 08:49:57,506::VLCRemote::DEBUG::<- Received: 16
2015-12-28 08:49:57,506::TraktForVLC::INFO::No tv show nor movie found for the current playing video
2015-12-28 08:50:02,512::VLCRemote::DEBUG::cleaning cache
2015-12-28 08:50:02,513::VLCRemote::DEBUG::<- Received: VLC media player 2.2.1 Terry Pratchett (Weatherwax)
Command Line Interface initialized. Type `help' for help.
>
2015-12-28 08:50:02,513::VLCRemote::DEBUG::-> Sending: is_playing
2015-12-28 08:50:02,513::VLCRemote::DEBUG::<- Received: 1
2015-12-28 08:50:02,513::VLCRemote::DEBUG::cleaning cache
2015-12-28 08:50:02,513::VLCRemote::DEBUG::<- Received: >
2015-12-28 08:50:02,513::VLCRemote::DEBUG::-> Sending: get_length
2015-12-28 08:50:02,513::VLCRemote::DEBUG::<- Received: 2848
2015-12-28 08:50:02,514::VLCRemote::DEBUG::cleaning cache
2015-12-28 08:50:02,514::VLCRemote::DEBUG::<- Received: >
2015-12-28 08:50:02,514::VLCRemote::DEBUG::-> Sending: get_title
2015-12-28 08:50:02,514::VLCRemote::DEBUG::<- Received: http://127.0.0.1:52104/
2015-12-28 08:50:02,514::VLCRemote::DEBUG::cleaning cache
2015-12-28 08:50:02,514::VLCRemote::DEBUG::<- Received: >
2015-12-28 08:50:02,514::VLCRemote::DEBUG::-> Sending: get_time
2015-12-28 08:50:02,514::VLCRemote::DEBUG::<- Received: 21
2015-12-28 08:50:02,514::TraktForVLC::INFO::No tv show nor movie found for the current playing video
2015-12-28 08:50:07,521::VLCRemote::DEBUG::cleaning cache
2015-12-28 08:50:07,521::VLCRemote::DEBUG::<- Received: VLC media player 2.2.1 Terry Pratchett (Weatherwax)
Command Line Interface initialized. Type `help' for help.>  
```

And here for example the name gets passed correctly...

```
2015-12-28 09:07:55,769::TraktForVLC::INFO::VERSION:TraktForVLC is up to date
2015-12-28 09:07:55,770::TraktForVLC::INFO::Logger level is set to DEBUG
2015-12-28 09:07:55,770::TraktForVLC::INFO::-- Will scrobble movies ? Yes
2015-12-28 09:07:55,770::TraktForVLC::INFO::-- Will scrobble tv shows ? Yes
2015-12-28 09:07:55,770::TraktForVLC::INFO::-- Will we mark movies as being watched ? Yes
2015-12-28 09:07:55,770::TraktForVLC::INFO::-- Will we mark tv shows as being watched ? Yes
2015-12-28 09:07:55,770::TraktForVLC::INFO::-- Videos will be scrobbled after 90% of their duration has been exceeded
2015-12-28 09:07:55,770::TraktForVLC::INFO::-- Timer set to 5 secs
2015-12-28 09:07:55,770::TraktForVLC::INFO::-- Video will be marked as "is watching" from 5 secs
2015-12-28 09:07:55,770::TraktForVLC::INFO::Listening VLC to localhost:4222
2015-12-28 09:07:55,770::TraktClient::DEBUG::TraktClient logger initialized
2015-12-28 09:07:55,770::TraktClient::DEBUG::TraktClient will use PIN Auth
2015-12-28 09:07:55,770::TraktForVLC::DEBUG::reset cache (None, None)
2015-12-28 09:07:55,774::VLCRemote::DEBUG::VLC version is 2.2.1
2015-12-28 09:07:55,774::VLCRemote::DEBUG::-> Sending: is_playing
2015-12-28 09:07:55,775::VLCRemote::DEBUG::<- Received: 1
2015-12-28 09:07:55,775::VLCRemote::DEBUG::cleaning cache
2015-12-28 09:07:55,775::VLCRemote::DEBUG::<- Received: >
2015-12-28 09:07:55,775::VLCRemote::DEBUG::-> Sending: get_length
2015-12-28 09:07:55,775::VLCRemote::DEBUG::<- Received: 6393
2015-12-28 09:07:55,776::VLCRemote::DEBUG::cleaning cache
2015-12-28 09:07:55,776::VLCRemote::DEBUG::<- Received: >
2015-12-28 09:07:55,776::VLCRemote::DEBUG::-> Sending: get_title
2015-12-28 09:07:55,776::VLCRemote::DEBUG::<- Received: Wish I Was Here
2015-12-28 09:07:55,777::VLCRemote::DEBUG::cleaning cache
2015-12-28 09:07:55,777::VLCRemote::DEBUG::<- Received: >
2015-12-28 09:07:55,777::VLCRemote::DEBUG::-> Sending: get_time
2015-12-28 09:07:55,777::VLCRemote::DEBUG::<- Received: 12
2015-12-28 09:07:55,777::TraktForVLC::DEBUG::main::New file: Wish I Was Here (6393)
2015-12-28 09:07:55,777::TraktForVLC::DEBUG::reset cache (Wish I Was Here, 6393)
2015-12-28 09:07:55,777::TraktForVLC::INFO::Not able to parse a tvshow from the file title
2015-12-28 09:07:55,777::TraktForVLC::INFO::No matching movie found for video playing
2015-12-28 09:07:55,777::TraktForVLC::DEBUG::get_Movie::Here's to help debug
Traceback (most recent call last):
  File "/Users/Alessandro/TraktForVLC/TraktForVLC.py", line 651, in get_Movie
    title = now_playing['title']
TypeError: 'bool' object has no attribute '__getitem__'
2015-12-28 09:07:55,778::TraktForVLC::INFO::No tv show nor movie found for the current playing video
2015-12-28 09:08:00,783::VLCRemote::DEBUG::cleaning cache
2015-12-28 09:08:00,783::VLCRemote::DEBUG::<- Received: VLC media player 2.2.1 Terry Pratchett (Weatherwax)
Command Line Interface initialized. Type `help' for help.
>
2015-12-28 09:08:00,783::VLCRemote::DEBUG::-> Sending: is_playing
2015-12-28 09:08:00,784::VLCRemote::DEBUG::<- Received: 1
2015-12-28 09:08:00,784::VLCRemote::DEBUG::cleaning cache
2015-12-28 09:08:00,784::VLCRemote::DEBUG::<- Received: >
2015-12-28 09:08:00,784::VLCRemote::DEBUG::-> Sending: get_length
2015-12-28 09:08:00,784::VLCRemote::DEBUG::<- Received: 6393
2015-12-28 09:08:00,784::VLCRemote::DEBUG::cleaning cache
2015-12-28 09:08:00,784::VLCRemote::DEBUG::<- Received: >
2015-12-28 09:08:00,784::VLCRemote::DEBUG::-> Sending: get_title
2015-12-28 09:08:00,784::VLCRemote::DEBUG::<- Received: Wish I Was Here
2015-12-28 09:08:00,785::VLCRemote::DEBUG::cleaning cache
2015-12-28 09:08:00,785::VLCRemote::DEBUG::<- Received: >
2015-12-28 09:08:00,785::VLCRemote::DEBUG::-> Sending: get_time
2015-12-28 09:08:00,785::VLCRemote::DEBUG::<- Received: 16
2015-12-28 09:08:00,785::TraktForVLC::INFO::No tv show nor movie found for the current playing video
2015-12-28 09:08:05,792::VLCRemote::DEBUG::cleaning cache
2015-12-28 09:08:05,792::VLCRemote::DEBUG::<- Received: VLC media player 2.2.1 Terry Pratchett (Weatherwax)
Command Line Interface initialized. Type `help' for help.
>
2015-12-28 09:08:05,792::VLCRemote::DEBUG::-> Sending: is_playing
2015-12-28 09:08:05,792::VLCRemote::DEBUG::<- Received: 1
2015-12-28 09:08:05,793::VLCRemote::DEBUG::cleaning cache
2015-12-28 09:08:05,793::VLCRemote::DEBUG::<- Received: >
2015-12-28 09:08:05,793::VLCRemote::DEBUG::-> Sending: get_length
2015-12-28 09:08:05,793::VLCRemote::DEBUG::<- Received: 6393
2015-12-28 09:08:05,793::VLCRemote::DEBUG::cleaning cache
2015-12-28 09:08:05,793::VLCRemote::DEBUG::<- Received: >
2015-12-28 09:08:05,793::VLCRemote::DEBUG::-> Sending: get_title
2015-12-28 09:08:05,793::VLCRemote::DEBUG::<- Received: Wish I Was Here
2015-12-28 09:08:05,793::VLCRemote::DEBUG::cleaning cache
2015-12-28 09:08:05,793::VLCRemote::DEBUG::<- Received: >
2015-12-28 09:08:05,794::VLCRemote::DEBUG::-> Sending: get_time
2015-12-28 09:08:05,794::VLCRemote::DEBUG::<- Received: 22
2015-12-28 09:08:05,794::TraktForVLC::INFO::No tv show nor movie found for the current playing video
^C2015-12-28 09:08:07,791::TraktForVLC::INFO::Program closed by SIGINT
```

**Comment by JimiC** [comment]
I think in your second example where the title is 'Wish I Was Here' you need to add the year (which is 2014) in the filename. So the filename should be "Wish I Was Here 2014".

**Comment by XaF** [comment]
@JimiC seems right for the second case, as it is possible the API doesn't identify the movie without the year.
For the first case, I would need more information about the file you are trying to play...

**Comment by XaF** [comment]
TraktForVLC 2.x makes that issue obsolete - #88
