### ISSUE TITLE
No tv show nor movie found for the current playing video

### ISSUE THREAD

**Issue by stoms12** [XaF/TraktForVLC#41]
It has been working up until now. Seems to be scrobbling TV shows, but not movies.
Can't work out what is wrong.

Here is my debug text:

```
Last login: Mon Feb 22 22:18:56 on ttys000
Sams-MBP:~ stoms$ ~/TraktForVLC-1.3.0/TraktForVLC.py --debug --small-timers
2016-02-22 22:21:36,151::TraktForVLC::INFO::## TraktForVLC v1.3.0-rc1 Breaking Bad
2016-02-22 22:21:36,151::TraktForVLC::INFO::## Copyright (C) 2014-2015  Raphaël Beamonte <raphael.beamonte@gmail.com>
2016-02-22 22:21:36,151::TraktForVLC::INFO::##
2016-02-22 22:21:36,151::TraktForVLC::INFO::## TraktForVLC is distributed in the hope that it will be useful, but
2016-02-22 22:21:36,151::TraktForVLC::INFO::## with ABSOLUTELY NO WARRANTY. This is free software; you are welcome
2016-02-22 22:21:36,151::TraktForVLC::INFO::## to redistribute and/or modify it under the terms of the GPL2.
2016-02-22 22:21:36,151::TraktForVLC::INFO::
2016-02-22 22:21:36,168::TraktForVLC::DEBUG::Running on Darwin-15.3.0-x86_64-i386-64bit, with Python 2.7.10
2016-02-22 22:21:36,217::requests.packages.urllib3.connectionpool::INFO::Starting new HTTPS connection (1): api.github.com
2016-02-22 22:21:37,735::requests.packages.urllib3.connectionpool::DEBUG::"GET /repos/XaF/TraktForVLC/releases HTTP/1.1" 200 None
2016-02-22 22:21:37,738::TraktForVLC::INFO::VERSION:TraktForVLC is up to date
2016-02-22 22:21:37,739::TraktForVLC::INFO::Logger level is set to DEBUG
2016-02-22 22:21:37,739::TraktForVLC::INFO::-- Will scrobble movies ? Yes
2016-02-22 22:21:37,739::TraktForVLC::INFO::-- Will scrobble tv shows ? Yes
2016-02-22 22:21:37,739::TraktForVLC::INFO::-- Will we mark movies as being watched ? Yes
2016-02-22 22:21:37,739::TraktForVLC::INFO::-- Will we mark tv shows as being watched ? Yes
2016-02-22 22:21:37,739::TraktForVLC::INFO::-- Videos will be scrobbled after 90% of their duration has been exceeded
2016-02-22 22:21:37,739::TraktForVLC::INFO::-- Timer set to 5 secs
2016-02-22 22:21:37,739::TraktForVLC::INFO::-- Video will be marked as "is watching" from 5 secs
2016-02-22 22:21:37,739::TraktForVLC::INFO::Listening VLC to localhost:4222
2016-02-22 22:21:37,740::TraktClient::DEBUG::TraktClient logger initialised
2016-02-22 22:21:37,740::TraktClient::DEBUG::TraktClient will use PIN Auth
2016-02-22 22:21:37,740::TraktForVLC::DEBUG::reset cache (None, None)
2016-02-22 22:21:37,744::VLCRemote::DEBUG::VLC version is 2.2.0
2016-02-22 22:21:37,744::VLCRemote::DEBUG::-> Sending: is_playing
2016-02-22 22:21:37,744::VLCRemote::DEBUG::<- Received: 1
2016-02-22 22:21:37,745::VLCRemote::DEBUG::cleaning cache
2016-02-22 22:21:37,745::VLCRemote::DEBUG::<- Received: >
2016-02-22 22:21:37,745::VLCRemote::DEBUG::-> Sending: get_length
2016-02-22 22:21:37,745::VLCRemote::DEBUG::<- Received: 6480
2016-02-22 22:21:37,746::VLCRemote::DEBUG::cleaning cache
2016-02-22 22:21:37,746::VLCRemote::DEBUG::<- Received: >
2016-02-22 22:21:37,746::VLCRemote::DEBUG::-> Sending: get_title
2016-02-22 22:21:37,746::VLCRemote::DEBUG::<- Received: Ex Machina 2015
2016-02-22 22:21:37,747::VLCRemote::DEBUG::cleaning cache
2016-02-22 22:21:37,747::VLCRemote::DEBUG::<- Received: >
2016-02-22 22:21:37,747::VLCRemote::DEBUG::-> Sending: get_time
2016-02-22 22:21:37,747::VLCRemote::DEBUG::<- Received: 17
2016-02-22 22:21:37,747::TraktForVLC::DEBUG::main::New file: Ex Machina 2015 (6480)
2016-02-22 22:21:37,747::TraktForVLC::DEBUG::reset cache (Ex Machina 2015, 6480)
2016-02-22 22:21:37,747::TraktForVLC::INFO::Not able to parse a tvshow from the file title
2016-02-22 22:21:37,748::TraktForVLC::DEBUG::get_Movie::Now playing: {'year': u'2015', 'title': u'Ex Machina'}
2016-02-22 22:21:37,750::requests.packages.urllib3.connectionpool::INFO::Starting new HTTP connection (1): www.imdbapi.com
2016-02-22 22:21:38,089::requests.packages.urllib3.connectionpool::DEBUG::"GET /?i=&y=2015&t=Ex+Machina&tomatoes=true HTTP/1.1" 200 701
2016-02-22 22:21:38,091::TraktForVLC::DEBUG::valid_Movie::no valid title found
Traceback (most recent call last):
  File "/Users/stoms/TraktForVLC-1.3.0/TraktForVLC.py", line 683, in valid_Movie
    movie = movie_info.get_movie_info(vlcTitle, vlcYear)
  File "/Users/stoms/TraktForVLC-1.3.0/movie_info.py", line 245, in get_movie_info
    output = response.json()
  File "/Users/stoms/TraktForVLC-1.3.0/requests/models.py", line 802, in son
    return json.loads(self.text, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
2016-02-22 22:21:38,093::TraktForVLC::INFO::No tv show nor movie found for the current playing video

**Comment by XaF** [comment]
This should be fixed by commit 9c9b4bdab9c14ed5ab11dad2b172c1fc121e9330 which is now included in the last release candidate.
