### ISSUE TITLE
TraktError: Unable to start movie: 500 Internal Server Error

### ISSUE THREAD

**Issue by pauloup** [XaF/TraktForVLC#42]
When I try to watch a movie in VLC I get a 500 Error:

``` sh
paulo@paulo-Aspire-5742:~$ /home/paulo/.track.tv/TraktForVLC-master/TraktForVLC.py --debug
2016-02-27 02:37:28,115::TraktForVLC::INFO::## TraktForVLC v1.3.0-rc1 Breaking Bad
2016-02-27 02:37:28,115::TraktForVLC::INFO::## Copyright (C) 2014-2015  Raphaël Beamonte <raphael.beamonte@gmail.com>
2016-02-27 02:37:28,115::TraktForVLC::INFO::##
2016-02-27 02:37:28,115::TraktForVLC::INFO::## TraktForVLC is distributed in the hope that it will be useful, but
2016-02-27 02:37:28,116::TraktForVLC::INFO::## with ABSOLUTELY NO WARRANTY. This is free software; you are welcome
2016-02-27 02:37:28,116::TraktForVLC::INFO::## to redistribute and/or modify it under the terms of the GPL2.
2016-02-27 02:37:28,116::TraktForVLC::INFO::
2016-02-27 02:37:28,119::TraktForVLC::DEBUG::Running on Linux-4.2.0-27-generic-x86_64-with-Ubuntu-15.10-wily, with Python 2.7.10
2016-02-27 02:37:28,150::requests.packages.urllib3.connectionpool::INFO::Starting new HTTPS connection (1): api.github.com
2016-02-27 02:37:29,058::requests.packages.urllib3.connectionpool::DEBUG::"GET /repos/XaF/TraktForVLC/releases HTTP/1.1" 200 None
2016-02-27 02:37:29,064::TraktForVLC::INFO::VERSION:TraktForVLC is up to date
2016-02-27 02:37:29,065::TraktForVLC::INFO::Logger level is set to DEBUG
2016-02-27 02:37:29,065::TraktForVLC::INFO::-- Will scrobble movies ? Yes
2016-02-27 02:37:29,065::TraktForVLC::INFO::-- Will scrobble tv shows ? Yes
2016-02-27 02:37:29,065::TraktForVLC::INFO::-- Will we mark movies as being watched ? Yes
2016-02-27 02:37:29,065::TraktForVLC::INFO::-- Will we mark tv shows as being watched ? Yes
2016-02-27 02:37:29,066::TraktForVLC::INFO::-- Videos will be scrobbled after 90% of their duration has been exceeded
2016-02-27 02:37:29,066::TraktForVLC::INFO::-- Timer set to 60 secs
2016-02-27 02:37:29,066::TraktForVLC::INFO::-- Video will be marked as "is watching" from 30 secs
2016-02-27 02:37:29,066::TraktForVLC::INFO::Listening VLC to localhost:4222
2016-02-27 02:37:29,066::TraktClient::DEBUG::TraktClient logger initialized
2016-02-27 02:37:29,066::TraktClient::DEBUG::TraktClient will use PIN Auth
2016-02-27 02:37:29,067::TraktForVLC::DEBUG::reset cache (None, None)
2016-02-27 02:37:29,069::VLCRemote::DEBUG::VLC version is 3.0.0-git
2016-02-27 02:37:29,069::VLCRemote::DEBUG::-> Sending: is_playing
2016-02-27 02:37:29,070::VLCRemote::DEBUG::<- Received: 0
2016-02-27 02:38:29,156::VLCRemote::DEBUG::VLC version is 3.0.0-git
2016-02-27 02:38:29,156::VLCRemote::DEBUG::-> Sending: is_playing
2016-02-27 02:38:29,157::VLCRemote::DEBUG::<- Received: 1
2016-02-27 02:38:29,157::VLCRemote::DEBUG::-> Sending: get_length
2016-02-27 02:38:29,201::VLCRemote::DEBUG::<- Received: > 5697
2016-02-27 02:38:29,203::VLCRemote::DEBUG::cleaning cache
2016-02-27 02:38:29,204::VLCRemote::DEBUG::<- Received: >
2016-02-27 02:38:29,204::VLCRemote::DEBUG::-> Sending: get_title
2016-02-27 02:38:29,205::VLCRemote::DEBUG::<- Received: Racing.Extinction.2015.720p.BluRay.x264-[YTS.AG].mp4
2016-02-27 02:38:29,206::VLCRemote::DEBUG::-> Sending: get_time
2016-02-27 02:38:29,249::VLCRemote::DEBUG::<- Received: > 45
2016-02-27 02:38:29,250::TraktForVLC::DEBUG::main::New file: Racing.Extinction.2015.720p.BluRay.x264-[YTS.AG].mp4 (5697)
2016-02-27 02:38:29,250::TraktForVLC::DEBUG::reset cache (Racing.Extinction.2015.720p.BluRay.x264-[YTS.AG].mp4, 5697)
2016-02-27 02:38:29,251::tvdb_api::DEBUG::Searching for show Racing%20Extinction
2016-02-27 02:38:29,251::tvdb_api::DEBUG::Retrieving URL http://thetvdb.com/api/GetSeries.php?seriesname=Racing%20Extinction&language=en
2016-02-27 02:38:30,021::TraktForVLC::DEBUG::valid_TV::no series found with the name 'Racing Extinction'
2016-02-27 02:38:30,023::TraktForVLC::DEBUG::get_Movie::Now playing: {'year': u'2015', 'title': u'Racing Extinction'}
2016-02-27 02:38:30,025::requests.packages.urllib3.connectionpool::INFO::Starting new HTTP connection (1): www.omdbapi.com
2016-02-27 02:38:30,262::requests.packages.urllib3.connectionpool::DEBUG::"GET /?i=&y=2015&t=Racing+Extinction&tomatoes=true HTTP/1.1" 200 None
2016-02-27 02:38:30,265::TraktForVLC::DEBUG::get_Movie::Valid movie found: {'Plot': u'A documentary that follows undercover activists trying to stave off a man-made mass extinction.', 'Title': u'Racing Extinction', 'imdbID': u'tt1618448', 'Director': u'Louie Psihoyos', 'tomatoRating': u'7.4', 'Year': u'2015', 'Runtime': u'90 min', 'imdbRating': u'8.1'}
2016-02-27 02:38:30,265::TraktForVLC::INFO::Racing Extinction state : 0%
2016-02-27 02:38:30,265::TraktForVLC::DEBUG::main::Video: {'duration': 5697, 'show_imdbid': None, 'episode': -1, 'title': u'Racing Extinction', 'tv': False, 'imdbid': u'tt1618448', 'percentage': 0, 'year': u'2015', 'season': -1}
2016-02-27 02:38:30,265::TraktForVLC::DEBUG::main::This video is scrobbled : False
2016-02-27 02:39:30,325::VLCRemote::DEBUG::VLC version is 3.0.0-git
2016-02-27 02:39:30,326::VLCRemote::DEBUG::-> Sending: is_playing
2016-02-27 02:39:30,326::VLCRemote::DEBUG::<- Received: 1
2016-02-27 02:39:30,326::VLCRemote::DEBUG::-> Sending: get_length
2016-02-27 02:39:30,365::VLCRemote::DEBUG::<- Received: > 5697
2016-02-27 02:39:30,365::VLCRemote::DEBUG::cleaning cache
2016-02-27 02:39:30,365::VLCRemote::DEBUG::<- Received: >
2016-02-27 02:39:30,365::VLCRemote::DEBUG::-> Sending: get_title
2016-02-27 02:39:30,366::VLCRemote::DEBUG::<- Received: Racing.Extinction.2015.720p.BluRay.x264-[YTS.AG].mp4
2016-02-27 02:39:30,366::VLCRemote::DEBUG::-> Sending: get_time
2016-02-27 02:39:30,405::VLCRemote::DEBUG::<- Received: > 106
2016-02-27 02:39:30,406::TraktForVLC::INFO::Racing Extinction state : 1%
2016-02-27 02:39:30,406::TraktForVLC::DEBUG::main::Video: {'duration': 5697, 'show_imdbid': None, 'episode': -1, 'title': u'Racing Extinction', 'tv': False, 'imdbid': u'tt1618448', 'percentage': 1, 'year': u'2015', 'season': -1}
2016-02-27 02:39:30,406::TraktForVLC::DEBUG::main::This video is scrobbled : False
2016-02-27 02:39:30,407::TraktForVLC::DEBUG::main::Trying to mark Racing Extinction watching on Trakt...
2016-02-27 02:39:30,407::TraktClient::DEBUG::Sending POST to https://api-v2launch.trakt.tv/scrobble/start data {"app_date": "2015-11-26", "movie": {"ids": {"imdb": "tt1618448"}}, "app_version": "1.3.0-rc1", "progress": 1}
2016-02-27 02:39:30,407::TraktClient::DEBUG::{"app_date": "2015-11-26", "movie": {"ids": {"imdb": "tt1618448"}}, "app_version": "1.3.0-rc1", "progress": 1}
2016-02-27 02:39:30,409::requests.packages.urllib3.connectionpool::INFO::Starting new HTTPS connection (1): api-v2launch.trakt.tv
2016-02-27 02:39:30,738::requests.packages.urllib3.connectionpool::DEBUG::"POST /scrobble/start HTTP/1.1" 500 97
2016-02-27 02:39:30,747::TraktForVLC::ERROR::An error occurred while trying to mark as watching Racing Extinction
Traceback (most recent call last):
  File "/home/paulo/.track.tv/TraktForVLC-master/TraktForVLC.py", line 555, in main
    self.get_episode(video))
  File "/home/paulo/.track.tv/TraktForVLC-master/TraktClient.py", line 420, in startWatching
    return self.__watching('start', imdb_id, progress, episode)
  File "/home/paulo/.track.tv/TraktForVLC-master/TraktClient.py", line 392, in __watching
    return self.__scrobble(action, data)
  File "/home/paulo/.track.tv/TraktForVLC-master/TraktClient.py", line 358, in __scrobble
    stream.reason))
TraktError: Unable to start movie: 500 Internal Server Error
```

**Comment by vedhavyas** [comment]
same issue here :+1:

**Comment by stoms12** [comment]
Same her also :+1: :(

**Comment by stoms12** [comment]
@XaF Same here also :+1: :(

**Comment by edmgt** [comment]
I'm also getting this.

**Comment by XaF** [comment]
Hmmm unfortunately, 500 errors don't come directly from TraktForVLC, but from Trakt.tv's servers.
Are you having those errors all the time and for any kind of thing you want to watch ?
Is this also happening when trying to mark as seen ?

**Comment by stoms12** [comment]
@XaF I seem to have sorted it for my install, however others may not have
I have been using a version of TraktForVLC downloaded 5th Jan. However it was having issues finding the correct movie title, see #41 . So I downloaded the version from the main page, TraktForVLC-master. This is when I started getting 500 errors when trying to mark shows/movies as watching on Trakt. I figured it was having issues with authenticating with my pin code from config.ini because after first install it didn't change to access_token and refresh_token.

I then copied the config.ini file from the previous version and have had no issues since.
Maybe you could go through and find what the problem is for other users with the same issue.
Happy to help here.

**Comment by XaF** [comment]
Seeing as the 500 error comes after a POST on `/scrobble/start`, the TraktClient should already be authenticated. @stoms12, do you remember if you were having issues with scrobbling also, or was it when logging in prior to scrobbling?

**Comment by XaF** [comment]
TraktForVLC 2.x makes that issue obsolete - #88
