### ISSUE TITLE
Could not find VLC running at localhost:4222

### ISSUE THREAD

**Issue by rcocchiararo** [XaF/TraktForVLC#43]
Hi

I am running VLC 2.2.2 x64, just downloaded TraktForVLC-master, configured and no go :p

I can "telnet localhost 4222" and it connects.

I downloaded python 2.7.11.

Debug log attached.

VLC is my backup for when KODI is unable to play some media or too slow for it, so i can try whatever version of vlc/python you sugest.

**Comment by rcocchiararo** [comment]
Ok, just downloaded vlc 2.2.0 x64 and python 2.7.9 x64 and it seems to work :+1: 

Will see if updating VLC keeps it working now.

**Comment by rcocchiararo** [comment]
Seems to work with 2.2.2 too, so 2.7.11 for python was the issue, i guess.

**Comment by rcocchiararo** [comment]
Will test more today, yesterday, after it worked with start_debugging, i tried with the normal start and it created a blank log file and did nothing :P

**Comment by rcocchiararo** [comment]
Ok, it does not work with any version :package: 

2016-03-01 19:35:53,267::VLCRemote::DEBUG::-> Sending: is_playing
2016-03-01 19:35:53,267::VLCRemote::DEBUG::<- Received: 1
2016-03-01 19:35:53,267::VLCRemote::DEBUG::-> Sending: get_length
2016-03-01 19:35:53,267::VLCRemote::DEBUG::<- Received: 2600
2016-03-01 19:35:53,267::VLCRemote::DEBUG::-> Sending: get_title
2016-03-01 19:35:53,269::VLCRemote::DEBUG::<- Received: The.Walking.Dead.S06E11.720p.WEB-DL.DD5.1.H264-RARBG
2016-03-01 19:35:53,269::VLCRemote::DEBUG::-> Sending: get_time
2016-03-01 19:35:53,269::VLCRemote::DEBUG::<- Received: 55
2016-03-01 19:35:53,269::TraktForVLC::INFO::The Walking Dead - 6x11 state : 2%
2016-03-01 19:35:53,269::TraktForVLC::DEBUG::main::Video: {'duration': 2600, 'show_imdbid': u'tt1520211', 'episode': u'11', 'title': u'The Walking Dead', 'tv': True, 'imdbid': u'tt4776070', 'percentage': 2, 'year': u'2010-10-31', 'season': u'6'}
2016-03-01 19:35:53,269::TraktForVLC::DEBUG::main::This video is scrobbled : False
2016-03-01 19:35:53,269::TraktForVLC::DEBUG::main::Trying to mark The Walking Dead - 6x11 watching on Trakt...
2016-03-01 19:35:53,269::TraktClient::DEBUG::Sending POST to https://api-v2launch.trakt.tv/scrobble/start data {"app_date": "2015-11-26", "progress": 2, "app_version": "1.3.0-rc1", "episode": {"season": "6", "number": "11"}, "show": {"ids": {"imdb": "tt1520211"}}}
2016-03-01 19:35:53,269::TraktClient::DEBUG::{"app_date": "2015-11-26", "progress": 2, "app_version": "1.3.0-rc1", "episode": {"season": "6", "number": "11"}, "show": {"ids": {"imdb": "tt1520211"}}}
2016-03-01 19:35:53,269::requests.packages.urllib3.connectionpool::INFO::Starting new HTTPS connection (1): api-v2launch.trakt.tv
2016-03-01 19:35:54,345::requests.packages.urllib3.connectionpool::DEBUG::"POST /scrobble/start HTTP/1.1" 500 97
2016-03-01 19:35:54,348::TraktForVLC::ERROR::An error occurred while trying to mark as watching The Walking Dead - 6x11
Traceback (most recent call last):
  File "C:\apps\TraktForVLC\TraktForVLC.py", line 555, in main
    self.get_episode(video))
  File "C:\apps\TraktForVLC\TraktClient.py", line 420, in startWatching
    return self.__watching('start', imdb_id, progress, episode)
  File "C:\apps\TraktForVLC\TraktClient.py", line 377, in __watching
    progress=progress)
  File "C:\apps\TraktForVLC\TraktClient.py", line 416, in __watchingEpisode
    return self.__scrobble(action, data)
  File "C:\apps\TraktForVLC\TraktClient.py", line 358, in __scrobble
    stream.reason))
TraktError: Unable to start episode: 500 Internal Server Error
2016-03-01 19:36:01,352::TraktForVLC::INFO::Could not find VLC running at localhost:4222
2016-03-01 19:36:01,352::TraktForVLC::DEBUG::Make sure your VLC player is running with --extraintf=rc --rc-host=localhost:4222 --rc-quiet
Traceback (most recent call last):
  File "C:\apps\TraktForVLC\TraktForVLC.py", line 408, in main
    vlc = VLCRemote(self.vlc_ip, self.vlc_port)
  File "C:\apps\TraktForVLC\vlcrc\__init__.py", line 38, in __init__
    self.cnx = telnetlib.Telnet(hostname, port)
  File "C:\Python27\lib\telnetlib.py", line 211, in __init__
    self.open(host, port, timeout)
  File "C:\Python27\lib\telnetlib.py", line 227, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "C:\Python27\lib\socket.py", line 571, in create_connection
    raise err

**Comment by XaF** [comment]
Well, when it's that kind of error, I can't really help! The error comes from the Trakt server directly!

**Comment by XaF** [comment]
TraktForVLC 2.x makes that issue obsolete - #88
