### ISSUE TITLE
TraktError: Unable to authenticate: 401 Unauthorized

### ISSUE THREAD

**Issue by GMFalka** [XaF/TraktForVLC#47]
Hey!

Tried to resolve this by reading back... but im out of ideas.
I ran the debug process and everything is working, but i get the dreaded 401 error...
I tried with new codes, restarted the process every time, whatmore i restarted the PC so im sure the process wasnt open while i changed PINs.

If you need more info, just ask!

`2016-03-21 23:38:29,354::requests.packages.urllib3.connectionpool::INFO::Starting new HTTPS connection (1): api-v2launch.trakt.tv
2016-03-21 23:38:29,868::requests.packages.urllib3.connectionpool::DEBUG::"POST /oauth/token HTTP/1.1" 401 169
2016-03-21 23:38:29,871::TraktForVLC::ERROR::An error occurred while trying to mark as watching Lie to Me - 2x17
Traceback (most recent call last):
  File "C:\Users\Falka\Desktop\TraktForVLC-master\TraktForVLC.py", line 555, in main
    self.get_episode(video))
  File "C:\Users\Falka\Desktop\TraktForVLC-master\TraktClient.py", line 420, in startWatching
    return self.__watching('start', imdb_id, progress, episode)
  File "C:\Users\Falka\Desktop\TraktForVLC-master\TraktClient.py", line 377, in __watching
    progress=progress)
  File "C:\Users\Falka\Desktop\TraktForVLC-master\TraktClient.py", line 416, in __watchingEpisode
    return self.__scrobble(action, data)
  File "C:\Users\Falka\Desktop\TraktForVLC-master\TraktClient.py", line 347, in __scrobble
    self.__get_access_token()
  File "C:\Users\Falka\Desktop\TraktForVLC-master\TraktClient.py", line 295, in __get_access_token
    stream.status_code, stream.reason))
TraktError: Unable to authenticate: 401 Unauthorized`

**Comment by XaF** [comment]
Hm, I really don't see where that could come from if you followed correctly the steps to add the PIN number. Do you have the line `PIN = xxxx` in your config file, xxxx being the pin number ?

**Comment by GMFalka** [comment]
Yeah, i rechecked the guide several times :/
Don't worry about it, i moved to mpc-hc! Thread can be closed!
