### ISSUE TITLE
Automatic start not working when VLC is not running on Mac

### ISSUE THREAD

**Issue by Mardaneus86** [XaF/TraktForVLC#50]
Launching the service on MacOS does not work with the following log message:

> 2016-05-18 00:11:07,037::TraktForVLC::INFO::Could not find VLC running at localhost:4222
2016-05-18 00:11:07,037::TraktForVLC::DEBUG::Make sure your VLC player is running with --extraintf=rc --rc-host=localhost:4222 --rc-quiet
Traceback (most recent call last):
  File "/Users/user/Applications/TraktForVLC/TraktForVLC.py", line 408, in main
    vlc = VLCRemote(self.vlc_ip, self.vlc_port)
  File "/Users/user/Applications/TraktForVLC/vlcrc/__init__.py", line 38, in __init__
    self.cnx = telnetlib.Telnet(hostname, port)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/telnetlib.py", line 211, in __init__
    self.open(host, port, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/telnetlib.py", line 227, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 61] Connection refused

This only happens when VLC is not running when the daemon is started. But since VLC is not started when the system boots, that's a problem. Any workaround possible?

By the way: when I launch the daemon while VLC is running, everything is working okay.

**Comment by XaF** [comment]
`TraktForVLC` tries regularly to contact VLC. It shows that message only in DEBUG mode (so, not an ERROR), and will show it every minute or so while your VLC is off. Sets only your logs to INFO if you do not want that much report.

**Comment by Mardaneus86** [comment]
Oh okay, must have been misjudging the debug message then. Thanks for your quick reply!
