### ISSUE TITLE
VLC Bad Return Error

### ISSUE THREAD

**Issue by ZooMas** [XaF/TraktForVLC#53]
Setup this plugin earlier today and I cannot get it to fully work. Running Windows 10. Tried multiple versions of Python (2.7.9 & 3.5.2) and multiple versions of VLC (2.2.0 & 2.2.4). Did fresh installs of them while clearing all the configs and nothing changed. Here is what I'm getting after inputting `python TraktForVLC.py --debug` into CMD:

`C:\Program Files (x86)\TraktForVLC>python TraktForVLC.py --debug
2016-07-30 15:58:16,208::TraktForVLC::INFO::## TraktForVLC v1.3.0-rc2 Breaking Bad
2016-07-30 15:58:16,210::TraktForVLC::INFO::## Copyright (C) 2014-2015  Raphael Beamonte <raphael.beamonte@gmail.com>
2016-07-30 15:58:16,212::TraktForVLC::INFO::##
2016-07-30 15:58:16,213::TraktForVLC::INFO::## TraktForVLC is distributed in the hope that it will be useful, but
2016-07-30 15:58:16,215::TraktForVLC::INFO::## with ABSOLUTELY NO WARRANTY. This is free software; you are welcome
2016-07-30 15:58:16,217::TraktForVLC::INFO::## to redistribute and/or modify it under the terms of the GPL2.
2016-07-30 15:58:16,219::TraktForVLC::INFO::
2016-07-30 15:58:16,222::TraktForVLC::DEBUG::Running on Windows-10-10.0.10586-SP0, with Python 3.5.2
2016-07-30 15:58:16,230::requests.packages.urllib3.connectionpool::INFO::Starting new HTTPS connection (1): api.github.com
2016-07-30 15:58:16,929::requests.packages.urllib3.connectionpool::DEBUG::"GET /repos/XaF/TraktForVLC/releases HTTP/1.1" 200 None
2016-07-30 15:58:16,934::TraktForVLC::INFO::VERSION:TraktForVLC is up to date
2016-07-30 15:58:16,936::TraktForVLC::INFO::Logger level is set to DEBUG
2016-07-30 15:58:16,937::TraktForVLC::INFO::-- Will scrobble movies ? Yes
2016-07-30 15:58:16,939::TraktForVLC::INFO::-- Will scrobble tv shows ? Yes
2016-07-30 15:58:16,940::TraktForVLC::INFO::-- Will we mark movies as being watched ? Yes
2016-07-30 15:58:16,941::TraktForVLC::INFO::-- Will we mark tv shows as being watched ? Yes
2016-07-30 15:58:16,943::TraktForVLC::INFO::-- Videos will be scrobbled after 90% of their duration has been exceeded
2016-07-30 15:58:16,945::TraktForVLC::INFO::-- Timer set to 60 secs
2016-07-30 15:58:16,946::TraktForVLC::INFO::-- Video will be marked as "is watching" from 30 secs
2016-07-30 15:58:16,948::TraktForVLC::INFO::Listening VLC to localhost:4222
2016-07-30 15:58:16,949::TraktClient::DEBUG::TraktClient logger initialized
2016-07-30 15:58:16,951::TraktClient::DEBUG::TraktClient will use PIN Auth
2016-07-30 15:58:16,952::TraktForVLC::DEBUG::reset cache (None, None)
2016-07-30 15:58:16,968::VLCRemote::DEBUG::cleaning cache
2016-07-30 15:58:16,980::VLCRemote::DEBUG::<- Received: b''
2016-07-30 15:58:16,981::VLCRemote::DEBUG::-> Sending: is_playing
2016-07-30 15:58:19,991::TraktForVLC::ERROR::An unknown error occurred
Traceback (most recent call last):
  File "TraktForVLC.py", line 398, in run
    self.main()
  File "TraktForVLC.py", line 435, in main
    vlcStatus = vlc.is_playing()
  File "C:\Program Files (x86)\TraktForVLC\vlcrc\__init__.py", line 152, in is_playing
    playing = self._command('is_playing', fn_re, raw=True)
  File "C:\Program Files (x86)\TraktForVLC\vlcrc\__init__.py", line 109, in _command
    'Pattern: %s\nReceived: %s' % (return_re.pattern, cmd_ret))
vlcrc.VLCBadReturn: Pattern: b'^(?!status change:)>?\\s*(?P<playing>\\d+)\r?\n'
Received: b''`

And then it proceeds to loop this part:
`2016-07-30 15:59:20,007::VLCRemote::DEBUG::cleaning cache
2016-07-30 15:59:20,008::VLCRemote::DEBUG::<- Received: b''
2016-07-30 15:59:20,009::VLCRemote::DEBUG::-> Sending: is_playing
2016-07-30 15:59:23,022::TraktForVLC::ERROR::An unknown error occurred
Traceback (most recent call last):
  File "TraktForVLC.py", line 398, in run
    self.main()
  File "TraktForVLC.py", line 435, in main
    vlcStatus = vlc.is_playing()
  File "C:\Program Files (x86)\TraktForVLC\vlcrc\__init__.py", line 152, in is_playing
    playing = self._command('is_playing', fn_re, raw=True)
  File "C:\Program Files (x86)\TraktForVLC\vlcrc\__init__.py", line 109, in _command
    'Pattern: %s\nReceived: %s' % (return_re.pattern, cmd_ret))
vlcrc.VLCBadReturn: Pattern: b'^(?!status change:)>?\\s*(?P<playing>\\d+)\r?\n'
Received: b''`

Any idea what could have went wrong? I setup the script and installed the necessary registry keys.

**Comment by XaF** [comment]
TraktForVLC 2.x makes that issue obsolete - #88
