### ISSUE TITLE
Can't scrobble :\

### ISSUE THREAD

**Issue by mich3lam** [XaF/TraktForVLC#63]
2017-02-22 11:45:30,243::VLCRemote::DEBUG::-> Sending: is_playing
2017-02-22 11:45:30,243::VLCRemote::DEBUG::<- Received: 1
2017-02-22 11:45:30,243::VLCRemote::DEBUG::-> Sending: get_length
2017-02-22 11:45:30,243::VLCRemote::DEBUG::<- Received: 1262
2017-02-22 11:45:30,243::VLCRemote::DEBUG::-> Sending: get_title
2017-02-22 11:45:30,244::VLCRemote::DEBUG::<- Received: Idiotsitter.S02E01.720p.HDTV.x264-FLEET.mkv
2017-02-22 11:45:30,244::VLCRemote::DEBUG::-> Sending: get_time
2017-02-22 11:45:30,244::VLCRemote::DEBUG::<- Received: 615
2017-02-22 11:45:30,244::TraktForVLC::INFO::Idiotsitter - 2x01 state : 48%
2017-02-22 11:45:30,244::TraktForVLC::DEBUG::main::Video: {'duration': 1262, 'show_imdbid': u'tt3532050', 'episode': u'1', 'title': u'Idiotsitter', 'tv': True, 'imdbid': None, 'percentage': 48, 'year': u'2016-01-14', 'season': u'2'}
2017-02-22 11:45:30,244::TraktForVLC::DEBUG::main::This video is scrobbled : False
2017-02-22 11:45:30,244::TraktForVLC::INFO::Scrobbling Idiotsitter - 2x01 to Trakt...
2017-02-22 11:45:30,244::TraktClient::DEBUG::Sending POST to https://api-v2launch.trakt.tv/scrobble/stop data {"app_date": "2016-05-03", "progress": 48, "app_version": "1.3.0-rc2", "episode": {"season": "2", "number": "1"}, "show": {"ids": {"imdb": "tt3532050"}}}
2017-02-22 11:45:30,246::TraktClient::DEBUG::{"app_date": "2016-05-03", "progress": 48, "app_version": "1.3.0-rc2", "episode": {"season": "2", "number": "1"}, "show": {"ids": {"imdb": "tt3532050"}}}
2017-02-22 11:45:30,246::requests.packages.urllib3.connectionpool::INFO::Starting new HTTPS connection (1): api-v2launch.trakt.tv
2017-02-22 11:45:30,661::requests.packages.urllib3.connectionpool::DEBUG::"POST /scrobble/stop HTTP/1.1" 404 None
2017-02-22 11:45:30,664::TraktForVLC::ERROR::An error occurred while trying to scrobble
Traceback (most recent call last):
  File "D:\Programs\TraktForVLC\TraktForVLC.py", line 533, in main
    self.get_episode(video))
  File "D:\Programs\TraktForVLC\TraktClient.py", line 424, in stopWatching
    return self.__watching('stop', imdb_id, progress, episode)
  File "D:\Programs\TraktForVLC\TraktClient.py", line 377, in __watching
    progress=progress)
  File "D:\Programs\TraktForVLC\TraktClient.py", line 416, in __watchingEpisode
    return self.__scrobble(action, data)
  File "D:\Programs\TraktForVLC\TraktClient.py", line 358, in __scrobble
    stream.reason))
TraktError: Unable to stop episode: 404 Not Found

This is what I get when it tries to send it as watched or whatever...Any ideas?

**Comment by XaF** [comment]
Do you have only a POST made to "scrobble/stop" in your log? Nothing before that?

**Comment by XaF** [comment]
TraktForVLC 2.x makes that issue obsolete - #88
