### ISSUE TITLE
running on win 10 and nothing happens :/ !

### ISSUE THREAD

**Issue by abdellatifbrhm** [XaF/TraktForVLC#65]
2017-03-26 23:50:29,055::TraktForVLC::INFO::## TraktForVLC v1.3.0-rc2 Breaking Bad
2017-03-26 23:50:29,055::TraktForVLC::INFO::## Copyright (C) 2014-2015  Raphael Beamonte <raphael.beamonte@gmail.com>
2017-03-26 23:50:29,056::TraktForVLC::INFO::##
2017-03-26 23:50:29,056::TraktForVLC::INFO::## TraktForVLC is distributed in the hope that it will be useful, but
2017-03-26 23:50:29,056::TraktForVLC::INFO::## with ABSOLUTELY NO WARRANTY. This is free software; you are welcome
2017-03-26 23:50:29,056::TraktForVLC::INFO::## to redistribute and/or modify it under the terms of the GPL2.
2017-03-26 23:50:29,057::TraktForVLC::INFO::
2017-03-26 23:50:29,058::TraktForVLC::DEBUG::Running on Windows-10-10.0.14986-SP0, with Python 3.5.3
2017-03-26 23:50:29,072::requests.packages.urllib3.connectionpool::INFO::Starting new HTTPS connection (1): api.github.com
2017-03-26 23:50:34,086::requests.packages.urllib3.connectionpool::DEBUG::"GET /repos/XaF/TraktForVLC/releases HTTP/1.1" 200 None
2017-03-26 23:50:37,107::TraktForVLC::INFO::VERSION:TraktForVLC is up to date
2017-03-26 23:50:37,110::TraktForVLC::INFO::Logger level is set to DEBUG
2017-03-26 23:50:37,110::TraktForVLC::INFO::-- Will scrobble movies ? Yes
2017-03-26 23:50:37,110::TraktForVLC::INFO::-- Will scrobble tv shows ? Yes
2017-03-26 23:50:37,110::TraktForVLC::INFO::-- Will we mark movies as being watched ? Yes
2017-03-26 23:50:37,110::TraktForVLC::INFO::-- Will we mark tv shows as being watched ? Yes
2017-03-26 23:50:37,111::TraktForVLC::INFO::-- Videos will be scrobbled after 90% of their duration has been exceeded
2017-03-26 23:50:37,111::TraktForVLC::INFO::-- Timer set to 5 secs
2017-03-26 23:50:37,111::TraktForVLC::INFO::-- Video will be marked as "is watching" from 5 secs
2017-03-26 23:50:37,111::TraktForVLC::INFO::Listening VLC to localhost:4222
2017-03-26 23:50:37,112::TraktClient::DEBUG::TraktClient logger initialized
2017-03-26 23:50:37,112::TraktClient::DEBUG::TraktClient will use PIN Auth
2017-03-26 23:50:37,113::TraktForVLC::DEBUG::reset cache (None, None)
2017-03-26 23:50:39,148::TraktForVLC::INFO::Could not find VLC running at localhost:4222
2017-03-26 23:50:39,148::TraktForVLC::DEBUG::Make sure your VLC player is running with --extraintf=rc --rc-host=localhost:4222 --rc-quiet
Traceback (most recent call last):
  File "C:\TraktForVLC-master\TraktForVLC.py", line 408, in main
    vlc = VLCRemote(self.vlc_ip, self.vlc_port)
  File "C:\TraktForVLC-master\vlcrc\__init__.py", line 38, in __init__
    self.cnx = telnetlib.Telnet(hostname, port)
  File "C:\Users\ibrah\AppData\Local\Programs\Python\Python35\lib\telnetlib.py", line 218, in __init__
    self.open(host, port, timeout)
  File "C:\Users\ibrah\AppData\Local\Programs\Python\Python35\lib\telnetlib.py", line 234, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "C:\Users\ibrah\AppData\Local\Programs\Python\Python35\lib\socket.py", line 712, in create_connection
    raise err
  File "C:\Users\ibrah\AppData\Local\Programs\Python\Python35\lib\socket.py", line 703, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

**Comment by XaF** [comment]
I think that VLC on Windows 10 does not allow the RC controller from what I've seen in the issues raised here. I would need confirmation however as I do not use Windows 10.

**Comment by XaF** [comment]
I'll close that issue, another one treats the same problem: #52
