### ISSUE TITLE
OMDB API is now private, and TraktForVLC cannot identify movies anymore

### ISSUE THREAD

**Issue by Dimsok** [XaF/TraktForVLC#66]
Doesn't scrobble for movies for which it did before. Series is ok.

**Comment by Dimsok** [comment]
2017-05-31 01:56:42,203::TraktForVLC::INFO::## TraktForVLC v1.3.0-rc2 Breaking Bad
2017-05-31 01:56:42,203::TraktForVLC::INFO::## Copyright (C) 2014-2015  Raphael Beamonte <raphael.beamonte@gmail.com>
2017-05-31 01:56:42,203::TraktForVLC::INFO::##
2017-05-31 01:56:42,203::TraktForVLC::INFO::## TraktForVLC is distributed in the hope that it will be useful, but
2017-05-31 01:56:42,203::TraktForVLC::INFO::## with ABSOLUTELY NO WARRANTY. This is free software; you are welcome
2017-05-31 01:56:42,203::TraktForVLC::INFO::## to redistribute and/or modify it under the terms of the GPL2.
2017-05-31 01:56:42,203::TraktForVLC::INFO::
2017-05-31 01:56:42,233::TraktForVLC::DEBUG::Running on Windows-XP-5.1.2600-SP3, with Python 2.7.2
2017-05-31 01:56:42,280::requests.packages.urllib3.connectionpool::INFO::Starting new HTTPS connection (1): api.github.com
2017-05-31 01:56:46,280::requests.packages.urllib3.connectionpool::DEBUG::"GET /repos/XaF/TraktForVLC/releases HTTP/1.1" 200 None
2017-05-31 01:56:46,546::TraktForVLC::INFO::VERSION:TraktForVLC is up to date
2017-05-31 01:56:46,546::TraktForVLC::INFO::Logger level is set to DEBUG
2017-05-31 01:56:46,546::TraktForVLC::INFO::-- Will scrobble movies ? Yes
2017-05-31 01:56:46,546::TraktForVLC::INFO::-- Will scrobble tv shows ? Yes
2017-05-31 01:56:46,546::TraktForVLC::INFO::-- Will we mark movies as being watched ? Yes
2017-05-31 01:56:46,546::TraktForVLC::INFO::-- Will we mark tv shows as being watched ? Yes
2017-05-31 01:56:46,546::TraktForVLC::INFO::-- Videos will be scrobbled after 90% of their duration has been exceeded
2017-05-31 01:56:46,546::TraktForVLC::INFO::-- Timer set to 5 secs
2017-05-31 01:56:46,546::TraktForVLC::INFO::-- Video will be marked as "is watching" from 5 secs
2017-05-31 01:56:46,546::TraktForVLC::INFO::Listening VLC to localhost:4222
2017-05-31 01:56:46,546::TraktClient::DEBUG::TraktClient logger initialized
2017-05-31 01:56:46,546::TraktClient::DEBUG::TraktClient will use PIN Auth
2017-05-31 01:56:46,546::TraktForVLC::DEBUG::reset cache (None, None)
2017-05-31 01:56:48,390::TraktForVLC::INFO::Could not find VLC running at localhost:4222
2017-05-31 01:56:48,390::TraktForVLC::DEBUG::Make sure your VLC player is running with --extraintf=rc --rc-host=localhost:4222 --rc-quiet
Traceback (most recent call last):
  File "c:\PROGRA~1\VideoLAN\VLC\TraktForVLC\TraktForVLC.py", line 408, in main
    vlc = VLCRemote(self.vlc_ip, self.vlc_port)
  File "c:\PROGRA~1\VideoLAN\VLC\TraktForVLC\vlcrc\__init__.py", line 38, in __init__
    self.cnx = telnetlib.Telnet(hostname, port)
  File "c:\Program Files\python\lib\telnetlib.py", line 209, in __init__
    self.open(host, port, timeout)
  File "c:\Program Files\python\lib\telnetlib.py", line 225, in open
    self.sock = socket.create_connection((host, port), timeout)
  File "c:\Program Files\python\lib\socket.py", line 571, in create_connection
    raise err
error: [Errno 10061] No connection could be made because the target machine actively refused it
2017-05-31 01:56:53,592::VLCRemote::DEBUG::-> Sending: is_playing
2017-05-31 01:56:53,625::VLCRemote::DEBUG::<- Received: 1
2017-05-31 01:56:53,625::VLCRemote::DEBUG::-> Sending: get_length
2017-05-31 01:56:53,625::VLCRemote::DEBUG::<- Received: 9297
2017-05-31 01:56:53,625::VLCRemote::DEBUG::-> Sending: get_title
2017-05-31 01:56:53,625::VLCRemote::DEBUG::<- Received: Pulp.Fiction.1994.720p.BrRip.x264.YIFY.mp4
2017-05-31 01:56:53,625::VLCRemote::DEBUG::-> Sending: get_time
2017-05-31 01:56:53,625::VLCRemote::DEBUG::<- Received: 0
2017-05-31 01:56:53,625::TraktForVLC::DEBUG::main::New file: Pulp.Fiction.1994.720p.BrRip.x264.YIFY.mp4 (9297)
2017-05-31 01:56:53,625::TraktForVLC::DEBUG::reset cache (Pulp.Fiction.1994.720p.BrRip.x264.YIFY.mp4, 9297)
2017-05-31 01:56:53,625::tvdb_api::DEBUG::Searching for show Pulp%20Fiction
2017-05-31 01:56:53,625::tvdb_api::DEBUG::Retrieving URL http://thetvdb.com/api/GetSeries.php?seriesname=Pulp%20Fiction&language=en
2017-05-31 01:56:56,390::TraktForVLC::DEBUG::valid_TV::no series found with the name 'Pulp Fiction'
2017-05-31 01:56:56,390::TraktForVLC::DEBUG::get_Movie::Now playing: {'year': u'1994', 'title': u'Pulp Fiction'}
2017-05-31 01:56:56,390::requests.packages.urllib3.connectionpool::INFO::Starting new HTTP connection (1): www.omdbapi.com
2017-05-31 01:58:40,375::requests.packages.urllib3.connectionpool::DEBUG::"GET /?i=&y=1994&t=Pulp+Fiction&tomatoes=true HTTP/1.1" 524 None
2017-05-31 01:58:40,375::TraktForVLC::DEBUG::valid_Movie::no valid title found
Traceback (most recent call last):
  File "c:\PROGRA~1\VideoLAN\VLC\TraktForVLC\TraktForVLC.py", line 684, in valid_Movie
    movie = movie_info.get_movie_info(vlcTitle, vlcYear)
  File "c:\PROGRA~1\VideoLAN\VLC\TraktForVLC\movie_info.py", line 245, in get_movie_info
    output = response.json()
  File "c:\PROGRA~1\VideoLAN\VLC\TraktForVLC\requests\models.py", line 802, in json
    return json.loads(self.text, **kwargs)
  File "c:\Program Files\python\lib\json\__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "c:\Program Files\python\lib\json\decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\Program Files\python\lib\json\decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
2017-05-31 01:58:40,437::TraktForVLC::INFO::No tv show nor movie found for the current playing video
2017-05-31 01:58:45,453::VLCRemote::DEBUG::-> Sending: is_playing
2017-05-31 01:58:45,453::VLCRemote::DEBUG::<- Received: 1
2017-05-31 01:58:45,453::VLCRemote::DEBUG::-> Sending: get_length
2017-05-31 01:58:45,467::VLCRemote::DEBUG::<- Received: status change: ( audio volume: 102 )

9297
2017-05-31 01:58:45,467::VLCRemote::DEBUG::-> Sending: get_title
2017-05-31 01:58:45,467::VLCRemote::DEBUG::<- Received: Pulp.Fiction.1994.720p.BrRip.x264.YIFY.mp4
2017-05-31 01:58:45,467::VLCRemote::DEBUG::-> Sending: get_time
2017-05-31 01:58:45,467::VLCRemote::DEBUG::<- Received: 84
2017-05-31 01:58:45,467::TraktForVLC::INFO::No tv show nor movie found for the current playing video
2017-05-31 01:58:50,515::VLCRemote::DEBUG::-> Sending: is_playing
2017-05-31 01:58:50,515::VLCRemote::DEBUG::<- Received: 1
2017-05-31 01:58:50,515::VLCRemote::DEBUG::-> Sending: get_length
2017-05-31 01:58:50,515::VLCRemote::DEBUG::<- Received: 9297
2017-05-31 01:58:50,515::VLCRemote::DEBUG::-> Sending: get_title
2017-05-31 01:58:50,515::VLCRemote::DEBUG::<- Received: Pulp.Fiction.1994.720p.BrRip.x264.YIFY.mp4
2017-05-31 01:58:50,515::VLCRemote::DEBUG::-> Sending: get_time
2017-05-31 01:58:50,515::VLCRemote::DEBUG::<- Received: 89
2017-05-31 01:58:50,515::TraktForVLC::INFO::No tv show nor movie found for the current playing video
2017-05-31 01:58:55,546::VLCRemote::DEBUG::-> Sending: is_playing
2017-05-31 01:58:55,546::VLCRemote::DEBUG::<- Received: 1
2017-05-31 01:58:55,546::VLCRemote::DEBUG::-> Sending: get_length
2017-05-31 01:58:55,546::VLCRemote::DEBUG::<- Received: 9297
2017-05-31 01:58:55,546::VLCRemote::DEBUG::-> Sending: get_title
2017-05-31 01:58:55,546::VLCRemote::DEBUG::<- Received: Pulp.Fiction.1994.720p.BrRip.x264.YIFY.mp4
2017-05-31 01:58:55,546::VLCRemote::DEBUG::-> Sending: get_time
2017-05-31 01:58:55,546::VLCRemote::DEBUG::<- Received: 94
2017-05-31 01:58:55,546::TraktForVLC::INFO::No tv show nor movie found for the current playing video
2017-05-31 01:59:00,546::VLCRemote::DEBUG::-> Sending: is_playing
2017-05-31 01:59:00,546::VLCRemote::DEBUG::<- Received: 1
2017-05-31 01:59:00,546::VLCRemote::DEBUG::-> Sending: get_length
2017-05-31 01:59:00,546::VLCRemote::DEBUG::<- Received: 9297
2017-05-31 01:59:00,546::VLCRemote::DEBUG::-> Sending: get_title
2017-05-31 01:59:00,562::VLCRemote::DEBUG::<- Received: Pulp.Fiction.1994.720p.BrRip.x264.YIFY.mp4
2017-05-31 01:59:00,562::VLCRemote::DEBUG::-> Sending: get_time
2017-05-31 01:59:00,562::VLCRemote::DEBUG::<- Received: 99
2017-05-31 01:59:00,562::TraktForVLC::INFO::No tv show nor movie found for the current playing video
2017-05-31 01:59:05,578::VLCRemote::DEBUG::-> Sending: is_playing
2017-05-31 01:59:05,578::VLCRemote::DEBUG::<- Received: 1
2017-05-31 01:59:05,578::VLCRemote::DEBUG::-> Sending: get_length
2017-05-31 01:59:05,578::VLCRemote::DEBUG::<- Received: 9297
2017-05-31 01:59:05,578::VLCRemote::DEBUG::-> Sending: get_title
2017-05-31 01:59:05,578::VLCRemote::DEBUG::<- Received: Pulp.Fiction.1994.720p.BrRip.x264.YIFY.mp4
2017-05-31 01:59:05,578::VLCRemote::DEBUG::-> Sending: get_time
2017-05-31 01:59:05,578::VLCRemote::DEBUG::<- Received: 104
2017-05-31 01:59:05,578::TraktForVLC::INFO::No tv show nor movie found for the current playing video
2017-05-31 01:59:10,592::VLCRemote::DEBUG::-> Sending: is_playing
2017-05-31 01:59:10,592::VLCRemote::DEBUG::<- Received: 1
2017-05-31 01:59:10,592::VLCRemote::DEBUG::-> Sending: get_length
2017-05-31 01:59:10,592::VLCRemote::DEBUG::<- Received: 9297
2017-05-31 01:59:10,592::VLCRemote::DEBUG::-> Sending: get_title
2017-05-31 01:59:10,592::VLCRemote::DEBUG::<- Received: Pulp.Fiction.1994.720p.BrRip.x264.YIFY.mp4
2017-05-31 01:59:10,592::VLCRemote::DEBUG::-> Sending: get_time
2017-05-31 01:59:10,592::VLCRemote::DEBUG::<- Received: 109
2017-05-31 01:59:10,608::TraktForVLC::INFO::No tv show nor movie found for the current playing video

**Comment by anoopsankar** [comment]
The reason seems to be because OMDB now requires an API key, so all requests are failing.

**Comment by Dimsok** [comment]
That means all other scrobblers for different players doesn't work for movies now? Or not all depend on OMDB?

Why not use opensubtitles.org for searching movie's title from hash? There is vroksub, which is using it to download sus
http://vrokolos.github.io/VrokSub/

**Comment by anoopsankar** [comment]
It could work, but then that's up to the repo developer to decide. You could fork the repo and try.

**Comment by XaF** [comment]
Thanks for that report! I'll update the title though to make it accurate with the problem. Thank you @anoopsankar for pinpointing the change for omdbapi. 

I do not know if using opensubtitles would be an interesting solution, but I'll search for a solution that could work and not be too format dependent. I'll check the options.

**Comment by Dimsok** [comment]
In comparison with previous workable omdbapi opensubtitles recognized more movies (which omdbapi didn't).

**Comment by XaF** [comment]
I contacted opensubtitles to get access to the API through a personnalized User-Agent as they requested it. If everything work out, I'll make a patch to use their API in `TraktForVLC`.

I'll probably look at other APIs also to have redundancy in the movie and tv shows identification for a future version of `TraktForVLC`.

**Comment by anoopsankar** [comment]
@XaF That seems to be the way to go. I would also recommend trying TMDBs search APIs; but again that requires an APIKey, so unsure how that could fit in.

**Comment by XaF** [comment]
I closed the issue as it is now fixed in version 1.x ; However, this will still be reorganized for 2.x releases when it happens.
