### ISSUE TITLE
MacOS: Doesn't seems to be linked with Trakt.tv 

### ISSUE THREAD

**Issue by Francis2b** [XaF/TraktForVLC#98]
I updated everything seems to go well but nothing appears on Trakt.tv when I'm watching something. Here is the log after the update/installation I have:

```
xxxxs-MacBook-Pro:~ xxxx$ cd /Users/xxxx/Desktop/
xxxxs-MacBook-Pro:Desktop xxxx$ chmod +x /Users/xxxx/Desktop/TraktForVLC_2.0.0a1.dev7.gf7d3c53_osx
xxxxs-MacBook-Pro:Desktop xxxx$ ./TraktForVLC_2.0.0a1.dev7.gf7d3c53_osx
2018-04-20 13:44:05,509::INFO::Searching for VLC binary...
2018-04-20 13:44:05,509::INFO::VLC binary: /Applications/VLC.app/Contents/MacOS/VLC
TraktForVLC will be installed for the following configuration:
 - OS: Darwin
 - VLC: /Applications/VLC.app/Contents/MacOS/VLC
 - VLC configuration: /Users/xxxx/Library/Preferences/org.videolan.vlc
 - VLC Lua: /Users/xxxx/Library/Application Support/org.videolan.vlc/lua
 - VLC Lua interface: /Users/xxxx/Library/Application Support/org.videolan.vlc/lua/intf
 - Service ? No
TraktForVLC is currently installed, replacing the current installed version will call 'uninstall' using the old binary, and 'install' with the new one.
Proceed with installation ? [y/n] y
2018-04-20 13:44:25,392::INFO::Uninstalling currently installed TraktForVLC
2018-04-20 13:44:25,862::INFO::UNINSTALL::INFO::VLC binary: /Applications/VLC.app/Contents/MacOS/VLC
2018-04-20 13:44:25,863::INFO::UNINSTALL::INFO::Searching for the files to remove in /Users/xxxx/Library/Application Support/org.videolan.vlc/lua
2018-04-20 13:44:25,863::INFO::UNINSTALL::INFO::Searching for the files to remove in /Users/xxxx/Library/Application Support/org.videolan.vlc/lua/intf
2018-04-20 13:44:25,863::INFO::UNINSTALL::INFO::Setting up VLC not to use trakt's interface
2018-04-20 13:44:26,000::INFO::UNINSTALL::INFO::VLC configured
2018-04-20 13:44:26,001::INFO::UNINSTALL::INFO::Removing /Users/xxxx/Library/Application Support/org.videolan.vlc/lua/intf/trakt.luac
2018-04-20 13:44:26,001::INFO::UNINSTALL::INFO::Removing /Users/xxxx/Library/Application Support/org.videolan.vlc/lua/trakt_helper
2018-04-20 13:44:26,001::INFO::UNINSTALL::INFO::TraktForVLC 2.0.0a1 is now uninstalled. :(
2018-04-20 13:44:26,087::INFO::Copying helper (trakt_helper) to /Users/xxxx/Library/Application Support/org.videolan.vlc/lua
2018-04-20 13:44:26,094::INFO::Copying trakt.luac to /Users/xxxx/Library/Application Support/org.videolan.vlc/lua/intf
2018-04-20 13:44:26,095::INFO::Configuration file exists, reading current values
2018-04-20 13:44:26,095::INFO::Update configuration version
2018-04-20 13:44:26,096::INFO::Setting up VLC to automatically use trakt's interface
2018-04-20 13:44:26,170::INFO::VLC configured
2018-04-20 13:44:26,170::INFO::TraktForVLC v2.0.0a1.dev7+gf7d3c53 is now installed. :D
```

**Comment by XaF** [comment]
If everything is installed well, the installation log is not useful at all... As everything went fine!
If you have a problem with a robbing, VLC logs are needed. But more importantly, nothing will appear on trakt.tv during the first 30 seconds of a media, as stated in the README configuration. So if that's your case, this is a non-issue!

**Comment by Francis2b** [comment]
I was watching a movie and checked after 50mins nothing on Trakt.tv here is the VLC log file:

```
main debug: VLC media player - 3.0.1 Vetinari
main debug: Copyright © 1996-2018 the VideoLAN team
main debug: revision 3.0.1-0-gec0f700fcc
main debug: configured with /Users/d-fu/vlc-3.0/extras/package/macosx/../../../configure  '--prefix=/Users/d-fu/vlc-3.0/release-3.0.1/vlc_install_dir' '--enable-macosx' '--enable-merge-ffmpeg' '--enable-osx-notifications' '--enable-faad' '--enable-flac' '--enable-theora' '--enable-shout' '--enable-ncurses' '--enable-twolame' '--enable-realrtsp' '--enable-libass' '--enable-macosx-qtkit' '--enable-macosx-avfoundation' '--disable-skins2' '--disable-xcb' '--disable-caca' '--disable-pulse' '--disable-sdl-image' '--disable-vnc' '--build=x86_64-apple-darwin17' '--host=x86_64-apple-darwin17' '--with-macosx-version-min=10.7' '--with-macosx-sdk=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk' '--with-breakpad=https://mac.crashes.videolan.org' 'build_alias=x86_64-apple-darwin17' 'host_alias=x86_64-apple-darwin17' 'CC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang' 'CFLAGS=-g' 'LDFLAGS=' 'CXX=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++' 'CXXFLAGS=-g' 'OBJC=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang' 'OBJCFLAGS=-g'
lua debug: (call_helper) Received response: {
    "date": "1524231712.774610",
    "format": "%s.%f",
    "timezone": "UTC"
}

lua info: Project X.mkv is paused! :| (3178.38009/5273.792)
lua debug: Timers ran: {
	["@trakt.lua:1521"] = false,
	["@trakt.lua:2299"] = false,
	["@trakt.lua:2540"] = false,
}
lua debug: (call_helper) Executing command: "/Users/Francois/Library/Application Support/org.videolan.vlc/lua/trakt_helper" "--quiet" "resolve" "--meta" "{\"filename\":\"Project X.mkv\"}" "--duration" "5273.792" "--hash" "a2b330104698b924" "--size" "8200154437"
lua debug: (call_helper) Received response: 2018-04-20 16:41:54,660::ERROR::min() arg is an empty sequence
Traceback (most recent call last):
  File "trakt_helper.py", line 75, in main
  File "helper/commands/resolve.py", line 830, in run
  File "helper/commands/resolve.py", line 758, in search_text
  File "helper/commands/resolve.py", line 658, in search_text_movie
ValueError: min() arg is an empty sequence
Traceback (most recent call last):
  File "trakt_helper.py", line 91, in <module>
  File "trakt_helper.py", line 75, in main
  File "helper/commands/resolve.py", line 830, in run
  File "helper/commands/resolve.py", line 758, in search_text
  File "helper/commands/resolve.py", line 658, in search_text_movie
ValueError: min() arg is an empty sequence
[36050] Failed to execute script trakt_helper

lua error: (call_helper) Command: "/Users/Francois/Library/Application Support/org.videolan.vlc/lua/trakt_helper" "--quiet" "resolve" "--meta" "{\"filename\":\"Project X.mkv\"}" "--duration" "5273.792" "--hash" "a2b330104698b924" "--size" "8200154437" 2>&1
lua error: (call_helper) Unable to parse json
lua error: (call_helper) Command output: 2018-04-20 16:41:54,660::ERROR::min() arg is an empty sequence
Traceback (most recent call last):
  File "trakt_helper.py", line 75, in main
  File "helper/commands/resolve.py", line 830, in run
  File "helper/commands/resolve.py", line 758, in search_text
  File "helper/commands/resolve.py", line 658, in search_text_movie
ValueError: min() arg is an empty sequence
Traceback (most recent call last):
  File "trakt_helper.py", line 91, in <module>
  File "trakt_helper.py", line 75, in main
  File "helper/commands/resolve.py", line 830, in run
  File "helper/commands/resolve.py", line 758, in search_text
  File "helper/commands/resolve.py", line 658, in search_text_movie
ValueError: min() arg is an empty sequence
[36050] Failed to execute script trakt_helper

lua debug: (call_helper) Executing command: "/Users/Francois/Library/Application Support/org.videolan.vlc/lua/trakt_helper" "date" "--format" "%s.%f"
main debug: toggling pause
main debug: toggling pause
main debug: toggling pause
macosx debug: Activated assertion NoDisplaySleepAssertion through IOKit (42810)
main debug: picture might be displayed late (missing 9 ms)
lua debug: (call_helper) Received response: {
    "date": "1524231715.281743",
    "format": "%s.%f",
    "timezone": "UTC"
}

lua info: Project X.mkv is playing! :) (3178.380090/5273.792000)
lua debug: Timers ran: {
	["@trakt.lua:1521"] = false,
	["@trakt.lua:2299"] = false,
	["@trakt.lua:2540"] = false,
}
lua debug: (call_helper) Executing command: "/Users/Francois/Library/Application Support/org.videolan.vlc/lua/trakt_helper" "--quiet" "resolve" "--meta" "{\"filename\":\"Project X.mkv\"}" "--duration" "5273.792" "--hash" "a2b330104698b924" "--size" "8200154437"
main debug: auto hiding mouse cursor
lua debug: (call_helper) Received response: 2018-04-20 16:41:57,215::ERROR::min() arg is an empty sequence
Traceback (most recent call last):
  File "trakt_helper.py", line 75, in main
  File "helper/commands/resolve.py", line 830, in run
  File "helper/commands/resolve.py", line 758, in search_text
  File "helper/commands/resolve.py", line 658, in search_text_movie
ValueError: min() arg is an empty sequence
Traceback (most recent call last):
  File "trakt_helper.py", line 91, in <module>
  File "trakt_helper.py", line 75, in main
  File "helper/commands/resolve.py", line 830, in run
  File "helper/commands/resolve.py", line 758, in search_text
  File "helper/commands/resolve.py", line 658, in search_text_movie
ValueError: min() arg is an empty sequence
[36070] Failed to execute script trakt_helper

lua error: (call_helper) Command: "/Users/Francois/Library/Application Support/org.videolan.vlc/lua/trakt_helper" "--quiet" "resolve" "--meta" "{\"filename\":\"Project X.mkv\"}" "--duration" "5273.792" "--hash" "a2b330104698b924" "--size" "8200154437" 2>&1
lua error: (call_helper) Unable to parse json
lua error: (call_helper) Command output: 2018-04-20 16:41:57,215::ERROR::min() arg is an empty sequence
Traceback (most recent call last):
  File "trakt_helper.py", line 75, in main
  File "helper/commands/resolve.py", line 830, in run
  File "helper/commands/resolve.py", line 758, in search_text
  File "helper/commands/resolve.py", line 658, in search_text_movie
ValueError: min() arg is an empty sequence
Traceback (most recent call last):
  File "trakt_helper.py", line 91, in <module>
  File "trakt_helper.py", line 75, in main
  File "helper/commands/resolve.py", line 830, in run
  File "helper/commands/resolve.py", line 758, in search_text
  File "helper/commands/resolve.py", line 658, in search_text_movie
ValueError: min() arg is an empty sequence
[36070] Failed to execute script trakt_helper

lua debug: (call_helper) Executing command: "/Users/Francois/Library/Application Support/org.videolan.vlc/lua/trakt_helper" "date" "--format" "%s.%f"
lua debug: (call_helper) Received response: {
    "date": "1524231717.828714",
    "format": "%s.%f",
    "timezone": "UTC"
}

lua info: Project X.mkv is playing! :) (3180.022326/5273.792000)
lua debug: Syncing past views with trakt
lua info: Syncing 0 movie(s) and 14 episode(s) with Trakt.tv
lua debug: (call_helper) Executing command: "/Users/Francois/Library/Application Support/org.videolan.vlc/lua/trakt_helper" "requests" "POST" "https://api.trakt.tv/sync/history" "--headers" "{\"Content-Type\":\"application/json\",\"trakt-api-key\":\"0e59f99095515c228d5fbc104e342574941aeeeda95946b8fa50b2b0366609bf\",\"User-Agent\":\"TraktForVLC 2.0.0a1.dev7+gf7d3c53/VLC 3.0.1 Vetinari\",\"trakt-api-version\":2,\"Authorization\":\"Bearer 138aaee420f7d1dbbc86947c9a803e01ce9462e8a2fb94ff76148eadf8a38a28\"}" "--data" "{\"episodes\":[{\"ids\":{\"imdb\":\"tt1425741\"},\"watched_at\":\"2018-04-18T12:23:02.206259Z\"},{\"ids\":{\"imdb\":\"tt1425711\"},\"watched_at\":\"2018-04-18T12:07:08.574552Z\"},{\"ids\":{\"imdb\":\"tt1425730\"},\"watched_at\":\"2018-04-17T18:37:10.537290Z\"},{\"ids\":{\"imdb\":\"tt1425690\"},\"watched_at\":\"2018-04-20T11:52:26.798372Z\"},{\"ids\":{\"imdb\":\"tt1425732\"},\"watched_at\":\"2018-04-17T18:33:30.765591Z\"},{\"ids\":{\"imdb\":\"tt1425681\"},\"watched_at\":\"2018-04-18T12:38:17.100868Z\"},{\"ids\":{\"imdb\":\"tt1425751\"},\"watched_at\":\"2018-04-17T18:26:25.054811Z\"},{\"ids\":{\"imdb\":\"tt0761727\"},\"watched_at\":\"2018-04-18T12:10:37.114806Z\"},{\"ids\":{\"imdb\":\"tt1425698\"},\"watched_at\":\"2018-04-17T18:29:54.762104Z\"},{\"ids\":{\"imdb\":\"tt1410647\"},\"watched_at\":\"2018-04-17T18:22:35.133480Z\"},{\"ids\":{\"imdb\":\"tt1425745\"},\"watched_at\":\"2018-04-18T12:15:23.499746Z\"},{\"ids\":{\"imdb\":\"tt0761721\"},\"watched_at\":\"2018-04-18T12:19:07.282382Z\"},{\"ids\":{\"imdb\":\"tt1425702\"},\"watched_at\":\"2018-04-18T12:34:00.184063Z\"},{\"ids\":{\"imdb\":\"tt1425689\"},\"watched_at\":\"2018-04-18T12:26:58.179574Z\"}]}"
lua debug: (call_helper) Received response: {
    "body": "{\"added\":{\"movies\":0,\"episodes\":0},\"not_found\":{\"movies\":[],\"shows\":[],\"seasons\":[],\"episodes\":[{\"watched_at\":\"2018-04-18T12:23:02.206259Z\",\"ids\":{\"imdb\":\"tt1425741\"}},{\"watched_at\":\"2018-04-18T12:07:08.574552Z\",\"ids\":{\"imdb\":\"tt1425711\"}},{\"watched_at\":\"2018-04-17T18:37:10.537290Z\",\"ids\":{\"imdb\":\"tt1425730\"}},{\"watched_at\":\"2018-04-20T11:52:26.798372Z\",\"ids\":{\"imdb\":\"tt1425690\"}},{\"watched_at\":\"2018-04-17T18:33:30.765591Z\",\"ids\":{\"imdb\":\"tt1425732\"}},{\"watched_at\":\"2018-04-18T12:38:17.100868Z\",\"ids\":{\"imdb\":\"tt1425681\"}},{\"watched_at\":\"2018-04-17T18:26:25.054811Z\",\"ids\":{\"imdb\":\"tt1425751\"}},{\"watched_at\":\"2018-04-18T12:10:37.114806Z\",\"ids\":{\"imdb\":\"tt0761727\"}},{\"watched_at\":\"2018-04-17T18:29:54.762104Z\",\"ids\":{\"imdb\":\"tt1425698\"}},{\"watched_at\":\"2018-04-17T18:22:35.133480Z\",\"ids\":{\"imdb\":\"tt1410647\"}},{\"watched_at\":\"2018-04-18T12:15:23.499746Z\",\"ids\":{\"imdb\":\"tt1425745\"}},{\"watched_at\":\"2018-04-18T12:19:07.282382Z\",\"ids\":{\"imdb\":\"tt0761721\"}},{\"watched_at\":\"2018-04-18T12:34:00.184063Z\",\"ids\":{\"imdb\":\"tt1425702\"}},{\"watched_at\":\"2018-04-18T12:26:58.179574Z\",\"ids\":{\"imdb\":\"tt1425689\"}}],\"people\":[]}}",
    "headers": {
        "CF-RAY": "40e85ffc096f25e0-MRS",
        "Cache-Control": "max-age=0, private, must-revalidate",
        "Cf-Railgun": "d38ee634da 99.99 0.166950 0030 e6be",
        "Connection": "keep-alive",
        "Content-Encoding": "gzip",
        "Content-Length": "346",
        "Content-Type": "application/json; charset=utf-8",
        "Date": "Fri, 20 Apr 2018 14:41:59 GMT",
        "Etag": "W/\"1545b13fdd292436310e4a19895f7c98\"",
        "Expect-CT": "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"",
        "Server": "cloudflare",
        "Set-Cookie": "__cfduid=dfc9d0a259af590a0426f94b444d2d68a1524235319; expires=Sat, 20-Apr-19 14:41:59 GMT; path=/; domain=.trakt.tv; HttpOnly",
        "Vary": "Accept-Encoding",
        "X-Content-Type-Options": "nosniff",
        "X-Frame-Options": "SAMEORIGIN",
        "X-Request-Id": "6776b862-e36b-4e29-82f5-e34506fb5685",
        "X-Runtime": "0.157256",
        "X-Xss-Protection": "1; mode=block"
    },
    "json": {
        "added": {
            "episodes": 0,
            "movies": 0
        },
        "not_found": {
            "episodes": [
                {
                    "ids": {
                        "imdb": "tt1425741"
                    },
                    "watched_at": "2018-04-18T12:23:02.206259Z"
                },
                {
                    "ids": {
                        "imdb": "tt1425711"
                    },
                    "watched_at": "2018-04-18T12:07:08.574552Z"
                },
                {
                    "ids": {
                        "imdb": "tt1425730"
                    },
                    "watched_at": "2018-04-17T18:37:10.537290Z"
                },
                {
                    "ids": {
                        "imdb": "tt1425690"
                    },
                    "watched_at": "2018-04-20T11:52:26.798372Z"
                },
                {
                    "ids": {
                        "imdb": "tt1425732"
                    },
                    "watched_at": "2018-04-17T18:33:30.765591Z"
                },
                {
                    "ids": {
                        "imdb": "tt1425681"
                    },
                    "watched_at": "2018-04-18T12:38:17.100868Z"
                },
                {
                    "ids": {
                        "imdb": "tt1425751"
                    },
                    "watched_at": "2018-04-17T18:26:25.054811Z"
                },
                {
                    "ids": {
                        "imdb": "tt0761727"
                    },
                    "watched_at": "2018-04-18T12:10:37.114806Z"
                },
                {
                    "ids": {
                        "imdb": "tt1425698"
                    },
                    "watched_at": "2018-04-17T18:29:54.762104Z"
                },
                {
                    "ids": {
                        "imdb": "tt1410647"
                    },
                    "watched_at": "2018-04-17T18:22:35.133480Z"
                },
                {
                    "ids": {
                        "imdb": "tt1425745"
                    },
                    "watched_at": "2018-04-18T12:15:23.499746Z"
                },
                {
                    "ids": {
                        "imdb": "tt0761721"
                    },
                    "watched_at": "2018-04-18T12:19:07.282382Z"
                },
                {
                    "ids": {
                        "imdb": "tt1425702"
                    },
                    "watched_at": "2018-04-18T12:34:00.184063Z"
                },
                {
                    "ids": {
                        "imdb": "tt1425689"
                    },
                    "watched_at": "2018-04-18T12:26:58.179574Z"
                }
            ],
            "movies": [],
            "people": [],
            "seasons": [],
            "shows": []
        }
    },
    "reason": "Created",
    "request": {
        "body": "{\"episodes\": [{\"watched_at\": \"2018-04-18T12:23:02.206259Z\", \"ids\": {\"imdb\": \"tt1425741\"}}, {\"watched_at\": \"2018-04-18T12:07:08.574552Z\", \"ids\": {\"imdb\": \"tt1425711\"}}, {\"watched_at\": \"2018-04-17T18:37:10.537290Z\", \"ids\": {\"imdb\": \"tt1425730\"}}, {\"watched_at\": \"2018-04-20T11:52:26.798372Z\", \"ids\": {\"imdb\": \"tt1425690\"}}, {\"watched_at\": \"2018-04-17T18:33:30.765591Z\", \"ids\": {\"imdb\": \"tt1425732\"}}, {\"watched_at\": \"2018-04-18T12:38:17.100868Z\", \"ids\": {\"imdb\": \"tt1425681\"}}, {\"watched_at\": \"2018-04-17T18:26:25.054811Z\", \"ids\": {\"imdb\": \"tt1425751\"}}, {\"watched_at\": \"2018-04-18T12:10:37.114806Z\", \"ids\": {\"imdb\": \"tt0761727\"}}, {\"watched_at\": \"2018-04-17T18:29:54.762104Z\", \"ids\": {\"imdb\": \"tt1425698\"}}, {\"watched_at\": \"2018-04-17T18:22:35.133480Z\", \"ids\": {\"imdb\": \"tt1410647\"}}, {\"watched_at\": \"2018-04-18T12:15:23.499746Z\", \"ids\": {\"imdb\": \"tt1425745\"}}, {\"watched_at\": \"2018-04-18T12:19:07.282382Z\", \"ids\": {\"imdb\": \"tt0761721\"}}, {\"watched_at\": \"2018-04-18T12:34:00.184063Z\", \"ids\": {\"imdb\": \"tt1425702\"}}, {\"watched_at\": \"2018-04-18T12:26:58.179574Z\", \"ids\": {\"imdb\": \"tt1425689\"}}]}",
        "headers": {
            "Accept": "*/*",
            "Accept-Encoding": "gzip, deflate",
            "Authorization": "Bearer 138aaee420f7d1dbbc86947c9a803e01ce9462e8a2fb94ff76148eadf8a38a28",
            "Connection": "keep-alive",
            "Content-Length": "1092",
            "Content-Type": "application/json",
            "User-Agent": "TraktForVLC 2.0.0a1.dev7+gf7d3c53/VLC 3.0.1 Vetinari",
            "trakt-api-key": "0e59f99095515c228d5fbc104e342574941aeeeda95946b8fa50b2b0366609bf",
            "trakt-api-version": "2"
        },
        "method": "POST",
        "url": "https://api.trakt.tv/sync/history"
    },
    "status_code": 201,
    "url": "https://api.trakt.tv/sync/history"
}

lua error: Media file:///Users/Francois/Desktop/Kaamelott/S03/Kaamelott - S03E36 - Feue la poule de guethenoc.mp4#234.104 (idx: 1) was not added to history
lua error: Media file:///Users/Francois/Desktop/Kaamelott/S03/Kaamelott - S03E31 - Le tournoi.mp4#210.095 (idx: 1) was not added to history
lua error: Media file:///Users/Francois/Desktop/Kaamelott/S03/Kaamelott - S03E05 - Séfriane d'Aquitaine.mp4#210.095 (idx: 1) was not added to history
lua error: Media file:///Users/Francois/Desktop/Kaamelott/S03/Kaamelott - S03E61 - La menace fantome.mp4#203.105 (idx: 1) was not added to history
lua error: Media file:///Users/Francois/Desktop/Kaamelott/S03/Kaamelott - S03E04 - Le porte bonheur.mp4#215.342 (idx: 1) was not added to history
lua error: Media file:///Users/Francois/Desktop/Kaamelott/S03/Kaamelott - S03E40 - La corne d'abondance.mp4#218.106 (idx: 1) was not added to history
lua error: Media file:///Users/Francois/Desktop/Kaamelott/S03/Kaamelott - S03E02 - L'aveu de bohort.mp4#223.121 (idx: 1) was not added to history
lua error: Media file:///Users/Francois/Desktop/Kaamelott/S03/Kaamelott - S03E32 - La pierre de lune.mp4#209.119 (idx: 1) was not added to history
lua error: Media file:///Users/Francois/Desktop/Kaamelott/S03/Kaamelott - S03E03 - Le magnanime.mp4#218.106 (idx: 1) was not added to history
lua error: Media file:///Users/Francois/Desktop/Kaamelott/S03/Kaamelott - S03E01 - Le chevalier errant.mp4#197.115 (idx: 1) was not added to history
lua error: Media file:///Users/Francois/Desktop/Kaamelott/S03/Kaamelott - S03E34 - Les cheveux noirs.mp4#221.101 (idx: 1) was not added to history
lua error: Media file:///Users/Francois/Desktop/Kaamelott/S03/Kaamelott - S03E35 - Dream on.mp4#224.12 (idx: 1) was not added to history
lua error: Media file:///Users/Francois/Desktop/Kaamelott/S03/Kaamelott - S03E39 - Les clous de la sainte croix.mp4#211.116 (idx: 1) was not added to history
lua error: Media file:///Users/Francois/Desktop/Kaamelott/S03/Kaamelott - S03E37 - Le repos du guerrier II.mp4#223.121 (idx: 1) was not added to history
lua debug: (call_helper) Executing command: "/Users/Francois/Library/Application Support/org.videolan.vlc/lua/trakt_helper" "--quiet" "extraids" "--episode" "Kaamelott" "3" "36" "2004" "--episode" "Kaamelott" "3" "31" "2004" "--episode" "Kaamelott" "3" "5" "2004" "--episode" "Kaamelott" "3" "61" "2004" "--episode" "Kaamelott" "3" "4" "2004" "--episode" "Kaamelott" "3" "40" "2004" "--episode" "Kaamelott" "3" "2" "2004" "--episode" "Kaamelott" "3" "32" "2004" "--episode" "Kaamelott" "3" "3" "2004" "--episode" "Kaamelott" "3" "1" "2004" "--episode" "Kaamelott" "3" "34" "2004" "--episode" "Kaamelott" "3" "35" "2004" "--episode" "Kaamelott" "3" "39" "2004" "--episode" "Kaamelott" "3" "37" "2004"
main debug: toggling resume
macosx debug: Releasing IOKit monitor sleep blocker (42810)
main debug: toggling resume
main debug: toggling resume
main debug: auto hiding mouse cursor
```

**Comment by XaF** [comment]
@Francis2b this is a different issue. Please do not post new issues into an already closed one!

**Comment by XaF** [comment]
Fix is ready for part of it.
There seem to be a problem for the "Kaamelott" tv shows as the First Air Date for TMDB is 2005, for TheTVDB is 2006, and for IMDB is 2004. The algorithm is thus unable to match them together as years differ. I cannot fix that in TraktForVLC without changing the algorithm to be more permissive, but that would allow for wrongful matches (which we already cannot guarantee won't happen).

**Comment by Francis2b** [comment]
Oh ok thank you for the advice. This afternoon I was watching Project X and it didn't appear.

**Comment by XaF** [comment]
That's the one I got the fix for. Your log was helpful for that!
I removed the tokens from the logs, but renewing them would still be better! :)

I will have to think about how I can proceed for things such as 'Kaamelott'.

**Comment by Francis2b** [comment]
For the cases like 'Kaamelott' I might have an idea but it may be a little bit heavy to add in the code.
If title the same in TVDB and IMDB but year different, then check the S1E1 title, if the same on both websites the show is the same.

It's just an idea I don't know anything in coding :/

**Comment by XaF** [comment]
I added a way to provide the already resolved IMDB ID, as the resolution failing for the series is actually of Trakt.tv's responsibility: they seem to be missing the IMDB IDs for those episodes on their side, and thus are unable to add them to history.

The attached PR (#99) should be able to solve both the movie and episode problems once released.
Thank you for the report!
